# Copyright 2024, Alejandro Colomar <alx@kernel.org>
# SPDX-License-Identifier: LGPL-3.0-only WITH LGPL-3.0-linking-exception


ifndef MAKEFILE_CONFIGURE_BUILD_DEPENDS_GROFF_BASE_PRECONV_INCLUDED
MAKEFILE_CONFIGURE_BUILD_DEPENDS_GROFF_BASE_PRECONV_INCLUDED := 1


DEFAULT_PRECONVFLAGS :=
PRECONVFLAGS         ?=
PRECONVFLAGS_        ?= $(DEFAULT_PRECONVFLAGS) $(PRECONVFLAGS)
PRECONV              ?= preconv


endif  # include guard
