.\" Copyright, The contributors to the Linux man-pages project
.\"
.\" SPDX-License-Identifier: GPL-2.0-or-later
.\"
.TH intro 6 (date) "Linux man-pages (unreleased)"
.SH NAME
intro \- introduction to games
.SH DESCRIPTION
Section 6 of the manual describes the games and funny little programs
available on the system.
.SH NOTES
.SS Authors and copyright conditions
Look at the header of the manual page source for the author(s) and copyright
conditions.
Note that these can be different from page to page!
