.\" Copyright, The contributors to the Linux man-pages project
.\"
.\" SPDX-License-Identifier: GPL-2.0-or-later
.\"
.TH intro 5 (date) "Linux man-pages (unreleased)"
.SH NAME
intro \- introduction to file formats and filesystems
.SH DESCRIPTION
Section 5 of the manual describes various file formats,
as well as the corresponding C structures, if any.
.P
In addition,
this section contains a number of pages that document various filesystems.
.SH NOTES
.SS Authors and copyright conditions
Look at the header of the manual page source for the author(s) and copyright
conditions.
Note that these can be different from page to page!
.SH SEE ALSO
.BR standards (7)
