.\" Copyright, The contributors to the Linux man-pages project
.\"
.\" SPDX-License-Identifier: GPL-2.0-or-later
.\"
.TH issue 5 (date) "Linux man-pages (unreleased)"
.SH NAME
issue \- prelogin message and identification file
.SH DESCRIPTION
.I /etc/issue
is a text file which contains a message or
system identification to be printed before the login prompt.
It may contain various
.BI @ char
and
.BI \[rs] char
sequences, if supported by the
.BR getty -type
program employed on the system.
.SH FILES
.I /etc/issue
.SH SEE ALSO
.BR motd (5),
.BR agetty (8),
.BR mingetty (8)
