.\" Copyright, the authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: GPL-2.0-or-later
.\"
.TH motd 5 (date) "Linux man-pages (unreleased)"
.SH NAME
motd \- message of the day
.SH DESCRIPTION
The contents of
.I /etc/motd
are displayed by
.BR login (1)
after a successful login but just before it executes the login shell.
.P
The abbreviation "motd" stands for "message of the day", and this file
has been traditionally used for exactly that (it requires much less disk
space than mail to all users).
.SH FILES
.I /etc/motd
.SH SEE ALSO
.BR login (1),
.BR issue (5)
