.\" Copyright, the authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_pid_uid_map 5 (date) "Linux man-pages (unreleased)"
.SH NAME
/proc/pid/gid_map, /proc/pid/uid_map \- user and group ID mappings
.SH DESCRIPTION
.TP
.IR /proc/ pid /gid_map " (since Linux 3.5)"
See
.BR user_namespaces (7).
.TP
.IR /proc/ pid /uid_map " (since Linux 3.5)"
See
.BR user_namespaces (7).
.SH SEE ALSO
.BR proc (5)
