.\" Copyright, The contributors to the Linux man-pages project
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_zoneinfo 5 (date) "Linux man-pages (unreleased)"
.SH NAME
/proc/zoneinfo \- memory zones
.SH DESCRIPTION
.TP
.IR /proc/zoneinfo " (since Linux 2.6.13)"
This file displays information about memory zones.
This is useful for analyzing virtual memory behavior.
.\" FIXME more should be said about /proc/zoneinfo
.SH SEE ALSO
.BR proc (5)
