.\" Copyright, The authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_malloc 5 (date) "Linux man-pages (unreleased)"
.SH NAME
/proc/malloc \- debug malloc (obsolete)
.SH DESCRIPTION
.TP
.IR /proc/malloc " (only up to and including Linux 2.2)"
.\" It looks like this only ever did something back in 1.0 days
This file is present only if
.B CONFIG_DEBUG_MALLOC
was defined during compilation.
.SH SEE ALSO
.BR proc (5)
