.\" Copyright, The contributors to the Linux man-pages project
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_sys_sunrpc 5 (date) "Linux man-pages (unreleased)"
.SH NAME
/proc/sys/sunrpc/ \- Sun remote procedure call for NFS
.SH DESCRIPTION
.TP
.I /proc/sys/sunrpc/
This directory supports Sun remote procedure call for network filesystem
(NFS).
On some systems, it is not present.
.SH SEE ALSO
.BR proc (5),
.BR proc_sys (5)
