.\" Copyright, The contributors to the Linux man-pages project
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_diskstats 5 (date) "Linux man-pages (unreleased)"
.SH NAME
/proc/diskstats \- disk I/O statistics
.SH DESCRIPTION
.TP
.IR /proc/diskstats " (since Linux 2.5.69)"
This file contains disk I/O statistics for each disk device.
See the Linux kernel source file
.I Documentation/admin\-guide/iostats.rst
(or
.I Documentation/iostats.txt
before Linux 5.3)
for further information.
.SH SEE ALSO
.BR proc (5)
