.\" Copyright, The authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_ioports 5 (date) "Linux man-pages (unreleased)"
.SH NAME
/proc/ioports \- I/O port regions
.SH DESCRIPTION
.TP
.I /proc/ioports
This is a list of currently registered Input-Output port regions that
are in use.
.SH SEE ALSO
.BR proc (5)
