.\" Copyright, The authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_pid_setgroups 5 (date) "Linux man-pages (unreleased)"
.SH NAME
/proc/pid/setgroups \- allow or deny setting groups
.SH DESCRIPTION
.TP
.IR /proc/ pid /setgroups " (since Linux 3.19)"
See
.BR user_namespaces (7).
.SH SEE ALSO
.BR proc (5)
