.\" Copyright, The contributors to the Linux man-pages project
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_execdomains 5 (date) "Linux man-pages (unreleased)"
.SH NAME
/proc/execdomains \- ABI personalities (obsolete)
.SH DESCRIPTION
.TP
.I /proc/execdomains
Used to list ABI personalities before Linux 4.1;
now contains a constant string for userspace compatibility.
.SH SEE ALSO
.BR proc (5)
