.\" Copyright, The contributors to the Linux man-pages project
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_sys_abi 5 (date) "Linux man-pages (unreleased)"
.SH NAME
/proc/sys/abi/ \- application binary information
.SH DESCRIPTION
.TP
.IR /proc/sys/abi/ " (since Linux 2.4.10)"
This directory may contain files with application binary information.
.\" On some systems, it is not present.
See the Linux kernel source file
.I Documentation/sysctl/abi.rst
(or
.I Documentation/sysctl/abi.txt
before Linux 5.3)
for more information.
.SH SEE ALSO
.BR proc (5),
.BR proc_sys (5)
