.\" Copyright, the authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_sys_proc 5 (date) "Linux man-pages (unreleased)"
.SH NAME
/proc/sys/proc/ \- ???
.SH DESCRIPTION
.TP
.I /proc/sys/proc/
This directory may be empty.
.SH SEE ALSO
.BR proc (5),
.BR proc_sys (5)
