.\" Copyright, The authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_sys_user 5 (date) "Linux man-pages (unreleased)"
.SH NAME
/proc/sys/user/ \- limits on the number of namespaces of various types
.SH DESCRIPTION
.TP
.IR /proc/sys/user/ " (since Linux 4.9)"
See
.BR namespaces (7).
.SH SEE ALSO
.BR proc (5),
.BR proc_sys (5)
