.\" Copyright, the authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_pid_numa_maps 5 (date) "Linux man-pages (unreleased)"
.SH NAME
/proc/pid/numa_maps \- NUMA memory policy and allocation
.SH DESCRIPTION
.TP
.IR /proc/ pid /numa_maps " (since Linux 2.6.14)"
See
.BR numa (7).
.SH SEE ALSO
.BR proc (5)
