.\" Copyright, the authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_dma 5 (date) "Linux man-pages (unreleased)"
.SH NAME
/proc/dma \- ISA DMA channels
.SH DESCRIPTION
.TP
.I /proc/dma
This is a list of the registered
.I ISA
DMA (direct memory access)
channels in use.
.SH SEE ALSO
.BR proc (5)
