.\" Copyright, The contributors to the Linux man-pages project
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_partitions 5 (date) "Linux man-pages (unreleased)"
.SH NAME
/proc/partitions \- major and minor numbers of partitions
.SH DESCRIPTION
.TP
.I /proc/partitions
Contains the major and minor numbers of each partition as well as the number
of 1024-byte blocks and the partition name.
.SH SEE ALSO
.BR proc (5)
