.\" Copyright, the authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_pid_cpuset 5 (date) "Linux man-pages (unreleased)"
.SH NAME
/proc/pid/cpuset \- CPU affinity sets
.SH DESCRIPTION
.TP
.IR /proc/ pid /cpuset " (since Linux 2.6.12)"
.\" and/proc/[pid]/task/[tid]/cpuset
See
.BR cpuset (7).
.SH SEE ALSO
.BR proc (5)
