.\" Copyright, The authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_slabinfo 5 (date) "Linux man-pages (unreleased)"
.SH NAME
/proc/slabinfo \- kernel caches
.SH DESCRIPTION
.TP
.I /proc/slabinfo
Information about kernel caches.
See
.BR slabinfo (5)
for details.
.SH SEE ALSO
.BR proc (5)
