.\" Copyright, The authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_apm 5 (date) "Linux man-pages (unreleased)"
.SH NAME
/proc/apm \- advanced power management
.SH DESCRIPTION
.TP
.I /proc/apm
Advanced power management version and battery information when
.B CONFIG_APM
is defined at kernel compilation time.
.SH SEE ALSO
.BR proc (5)
