.\" Copyright, The contributors to the Linux man-pages project
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_fb 5 (date) "Linux man-pages (unreleased)"
.SH NAME
/proc/fb \- frame buffer
.SH DESCRIPTION
.TP
.I /proc/fb
Frame buffer information when
.B CONFIG_FB
is defined during kernel compilation.
.SH SEE ALSO
.BR proc (5)
