.\" Copyright, the authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_cpuinfo 5 (date) "Linux man-pages (unreleased)"
.SH NAME
/proc/cpuinfo \- CPU and system architecture information
.SH DESCRIPTION
.TP
.I /proc/cpuinfo
This is a collection of CPU and system architecture dependent items,
for each supported architecture a different list.
Two common entries are
.I processor
which gives CPU number and
.IR bogomips ;
a system constant that is calculated
during kernel initialization.
SMP machines have information for
each CPU.
The
.BR lscpu (1)
command gathers its information from this file.
.SH SEE ALSO
.BR proc (5)
