.\" Copyright, the authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_devices 5 (date) "Linux man-pages (unreleased)"
.SH NAME
/proc/devices \- major numbers and device groups
.SH DESCRIPTION
.TP
.I /proc/devices
Text listing of major numbers and device groups.
This can be used by MAKEDEV scripts for consistency with the kernel.
.SH SEE ALSO
.BR proc (5)
