.\" Copyright, The authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_sys_dev 5 (date) "Linux man-pages (unreleased)"
.SH NAME
/proc/sys/dev/ \- device-specific information
.SH DESCRIPTION
.TP
.I /proc/sys/dev/
This directory contains device-specific information (e.g.,
.IR dev/cdrom/info ).
On
some systems, it may be empty.
.SH SEE ALSO
.BR proc (5),
.BR proc_sys (5)
