.\" Copyright, the authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.TH cachestat 2 (date) "Linux man-pages (unreleased)"
.SH NAME
cachestat \- query the page cache statistics of a file
.SH SYNOPSIS
.nf
.B #include <sys/mman.h>
.PP
.B struct cachestat_range {
.BR "    __u64 off;"
.BR "    __u64 len;"
.RE
.B };
.PP
.B struct cachestat {
.BR "    __u64 nr_cache;"
.BR "    __u64 nr_dirty;"
.BR "    __u64 nr_writeback;"
.BR "    __u64 nr_evicted;"
.BR "    __u64 nr_recently_evicted;"
.B };
.PP
.BI "int cachestat(unsigned int " fd ", struct cachestat_range *" cstat_range ","
.br
.BI "              struct cachestat *" cstat ", unsigned int " flags ");"
.nf
.SH DESCRIPTION
.B cachestat()
queries the number of cached pages, dirty pages,
pages marked for writeback, evicted pages,
and recently evicted pages in the byte range specified by
.I .off
and
.I .len
in the
.B cachestat_range
structure.
.P
An evicted page is one that was previously in the page cache
but has since been evicted.
A page is considered recently evicted if its reentry into the cache
would indicate active usage under memory pressure.
.PP
The results are returned in a
.B cachestat
structure, pointed to by the
.I cstat
argument.
.PP
The
.I .off
and
.I .len
fields must be non-negative. If
.I .len > 0
, the queried range is
.RI [ .off ,\~ .off+.len ]
. If
.IR len\~==\~0 ,
the range is from
.I .off
to the end of the file.
.PP
The
.I flags
argument is reserved for future use and must be set to
.BR 0 .
.
.PP
Currently,
.B hugetlbfs
files are not supported.
.PP
Note that the status of a page may change after
.B cachestat()
retrieves it but before the values are returned to the application;
thus, the values may be slightly outdated.
.SH RETURN VALUE
On success,
.B cachestat()
returns 0. On error, \-1 is returned and
.I errno
is set appropriately.
.SH ERRORS
.TP
.B EFAULT
.I cstat
or
.I cstat_range
point to an invalid address.
.TP
.B EINVAL
Invalid
.I flags
value.
.TP
.B EBADF
Invalid file descriptor.
.TP
.B EOPNOTSUPP
The file descriptor refers to a
.B hugetlbfs
file, which is unsupported.
