.\" Copyright (c) 2017 by Michael Kerrisk <mtk.manpages@gmail.com>
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.\"
.TH ioctl_nsfs 2 (date) "Linux man-pages (unreleased)"
.SH NAME
ioctl_nsfs
\-
ioctl() operations for Linux namespaces
.SH DESCRIPTION
.SS Discovering namespace relationships
.TP
.B NS_GET_USERNS
.TQ
.B NS_GET_PARENT
.SS Discovering the namespace type
.TP
.B NS_GET_NSTYPE
.SS Discovering the owner of a user namespace
.TP
.B NS_GET_OWNER_UID
.SH ERRORS
Any of the above
.BR ioctl ()
operations can return the following errors:
.TP
.B ENOTTY
.I fd
does not refer to a
.IR /proc/ pid /ns/ *
file.
.SH STANDARDS
Linux.
.SH SEE ALSO
.BR ioctl (2),
.BR NS_GET_USERNS (2const),
.BR NS_GET_PARENT (2const),
.BR NS_GET_NSTYPE (2const),
.BR NS_GET_OWNER_UID (2const),
.BR fstat (2),
.BR proc (5),
.BR namespaces (7)
