.\" Copyright 2002, Walter Harms <walter.harms@informatik.uni-oldenburg.de>
.\" Copyright 2002, Andries Brouwer <aeb@cwi.nl>
.\" Copyright 2024, Alejandro Colomar <alx@kernel.org>
.\"
.\" SPDX-License-Identifier: GPL-1.0-or-later
.\"
.TH ioctl_tty 2 (date) "Linux man-pages (unreleased)"
.SH NAME
ioctl_tty \- ioctls for terminals and serial lines
.SH LIBRARY
Standard C library
.RI ( libc ", " \-lc )
.SH SYNOPSIS
.nf
.BR "#include <asm/termbits.h>" "  /* Definition of constants */"
.B #include <sys/ioctl.h>
.P
.BI "int ioctl(int " fd ", int " op ", ...);"
.fi
.SH DESCRIPTION
The
.BR ioctl (2)
call for terminals and serial ports accepts many possible operation arguments.
Most require a third argument, of varying type, here called
.I argp
or
.IR arg .
.P
Use of
.BR ioctl ()
makes for nonportable programs.
Use the POSIX interface described in
.BR termios (3)
whenever possible.
.SS Get and set terminal attributes
.TP
.B TCGETS
.TQ
.B TCSETS
.TQ
.B TCSETSW
.TQ
.B TCSETSF
.TP
.B TCGETS
.TQ
.B TCSETS
.TQ
.B TCSETSW
.TQ
.B TCSETSF
.TP
.B TCGETS
.TQ
.B TCSETS
.TQ
.B TCSETSW
.TQ
.B TCSETSF
.SS Locking the termios structure
.TP
.B TIOCGLCKTRMIOS
.TQ
.B TIOCSLCKTRMIOS
.SS Get and set window size
.TP
.B TIOCGWINSZ
.TQ
.B TIOCSWINSZ
.SS Sending a break
.TP
.B TCSBRK
.TQ
.B TCSBRKP
.TQ
.B TIOCSBRK
.TQ
.B TIOCCBRK
.SS Software flow control
.TP
.B TCXONC
.SS Buffer count and flushing
.TP
.B FIONREAD
.TQ
.B TIOCINQ
.TQ
.B TIOCOUTQ
.TQ
.B TCFLSH
.TQ
.B TIOCSERGETLSR
.SS Faking input
.TP
.B TIOCSTI
.SS Redirecting console output
.TP
.B TIOCCONS
.SS Controlling terminal
.TP
.B TIOCSCTTY
.TQ
.B TIOCNOTTY
.SS Process group and session ID
.TP
.B TIOCGPGRP
.TQ
.B TIOCSPGRP
.TQ
.B TIOCGSID
.SS Exclusive mode
.TP
.B TIOCEXCL
.TQ
.B TIOCGEXCL
.TQ
.B TIOCNXCL
.SS Line discipline
.TP
.B TIOCGETD
.TQ
.B TIOCSETD
.SS Pseudoterminal ioctls
.TP
.B TIOCPKT
.TQ
.B TIOCGPKT
.TP
.B TIOCSPTLCK
.TQ
.B TIOCGPTLCK
.TP
.B TIOCGPTPEER
.SS Modem control
.TP
.B TIOCMGET
.TQ
.B TIOCMSET
.TQ
.B TIOCMBIC
.TQ
.B TIOCMBIS
.TP
.B TIOCMIWAIT
.TP
.B TIOCGICOUNT
.SS Marking a line as local
.TP
.B TIOCGSOFTCAR
.TQ
.B TIOCSSOFTCAR
.SS Linux-specific
For the
.B TIOCLINUX
ioctl, see
.BR ioctl_console (2).
.SS Kernel debugging
.TP
.B TIOCTTYGSTRUCT
.\" .SS Serial info
.\" .BR "#include <linux/serial.h>"
.\" .P
.\" .TP
.\" .BI "TIOCGSERIAL	struct serial_struct *" argp
.\" Get serial info.
.\" .TP
.\" .BI "TIOCSSERIAL	const struct serial_struct *" argp
.\" Set serial info.
.SH RETURN VALUE
On success,
0 is returned.
On error,
\-1 is returned, and
.I errno
is set to indicate the error.
.SH SEE ALSO
.BR ioctl (2),
.BR TCGETS (2const),
.BR TCSETS (2const),
.BR TCSETSW (2const),
.BR TCSETSF (2const),
.BR TCGETS (2const),
.BR TCSETS (2const),
.BR TCSETSW (2const),
.BR TCSETSF (2const),
.BR TCGETS (2const),
.BR TCSETS (2const),
.BR TCSETSW (2const),
.BR TCSETSF (2const),
.BR TIOCGLCKTRMIOS (2const),
.BR TIOCSLCKTRMIOS (2const),
.BR TIOCGWINSZ (2const),
.BR TIOCSWINSZ (2const),
.BR TCSBRK (2const),
.BR TCSBRKP (2const),
.BR TIOCSBRK (2const),
.BR TIOCCBRK (2const),
.BR TCXONC (2const),
.BR FIONREAD (2const),
.BR TIOCINQ (2const),
.BR TIOCOUTQ (2const),
.BR TCFLSH (2const),
.BR TIOCSERGETLSR (2const),
.BR TIOCSTI (2const),
.BR TIOCCONS (2const),
.BR TIOCSCTTY (2const),
.BR TIOCNOTTY (2const),
.BR TIOCGPGRP (2const),
.BR TIOCSPGRP (2const),
.BR TIOCGSID (2const),
.BR TIOCEXCL (2const),
.BR TIOCGEXCL (2const),
.BR TIOCNXCL (2const),
.BR TIOCPKT (2const),
.BR TIOCGPKT (2const),
.BR TIOCSPTLCK (2const),
.BR TIOCGPTLCK (2const),
.BR TIOCGPTPEER (2const),
.BR TIOCMGET (2const),
.BR TIOCMSET (2const),
.BR TIOCMBIC (2const),
.BR TIOCMBIS (2const),
.BR TIOCMIWAIT (2const),
.BR TIOCGICOUNT (2const),
.BR TIOCGSOFTCAR (2const),
.BR TIOCSSOFTCAR (2const),
.BR TIOCTTYGSTRUCT (2const),
.BR ldattach (8),
.BR ioctl_console (2),
.BR termios (3),
.BR pty (7)
.\"
.\" FIONBIO			const int *
.\" FIONCLEX			void
.\" FIOCLEX			void
.\" FIOASYNC			const int *
.\" from serial.c:
.\" TIOCSERCONFIG		void
.\" TIOCSERGWILD		int *
.\" TIOCSERSWILD		const int *
.\" TIOCSERGSTRUCT		struct async_struct *
.\" TIOCSERGETMULTI		struct serial_multiport_struct *
.\" TIOCSERSETMULTI		const struct serial_multiport_struct *
.\" TIOCGSERIAL, TIOCSSERIAL (see above)
