.\" Copyright 1995, Jim Van Zandt <jrv@vanzandt.mv.com> and aeb
.\" Copyright 1995, <faith@cs.unc.edu>
.\" Copyright 1995, <jrv@vanzandt.mv.com>
.\" Copyright 1995, "H. Peter Anvin" <hpa@storm.net>
.\" Copyright 2024, Alejandro Colomar <alx@kernel.org>
.\"
.\" SPDX-License-Identifier: GPL-2.0-or-later
.\"
.TH ioctl_console 2 (date) "Linux man-pages (unreleased)"
.SH NAME
ioctl_console \- ioctls for console terminal and virtual consoles
.SH SYNOPSIS
.nf
.B #include <sys/ioctl.h>
.P
.BI "int ioctl(int " fd ", unsigned long " op ", ...);"
.fi
.SH DESCRIPTION
The following Linux-specific
.BR ioctl (2)
operations are supported for console terminals and virtual consoles.
.TP
.B KDGETLED
.TQ
.B KDSETLED
.TQ
.B KDGKBLED
.TQ
.B KDSKBLED
.TQ
.B KDGKBTYPE
.TQ
.B KDADDIO
.TQ
.B KDDELIO
.TQ
.B KDENABIO
.TQ
.B KDDISABIO
.TQ
.B KDSETMODE
.TQ
.B KDGETMODE
.TQ
.B KDMKTONE
.TQ
.B KIOCSOUND
.TQ
.B GIO_CMAP
.TQ
.B PIO_CMAP
.TQ
.B GIO_FONT
.TQ
.B GIO_FONTX
.TQ
.B PIO_FONT
.TQ
.B PIO_FONTX
.TQ
.B PIO_FONTRESET
.TQ
.B GIO_SCRNMAP
.TQ
.B GIO_UNISCRNMAP
.TQ
.B PIO_SCRNMAP
.TQ
.B PIO_UNISCRNMAP
.TQ
.B GIO_UNIMAP
.TQ
.B PIO_UNIMAP
.TQ
.B PIO_UNIMAPCLR
.TQ
.B KDGKBMODE
.TQ
.B KDSKBMODE
.TQ
.B KDGKBMETA
.TQ
.B KDSKBMETA
.TQ
.B KDGKBENT
.TQ
.B KDSKBENT
.TQ
.B KDGKBSENT
.TQ
.B KDSKBSENT
.TQ
.B KDGKBDIACR
.TQ
.B KDGETKEYCODE
.TQ
.B KDSETKEYCODE
.TQ
.B KDSIGACCEPT
See
.BR ioctl_kd (2).
.TP
.B TIOCLINUX
.TP
.B VT_OPENQRY
.TQ
.B VT_GETMODE
.TQ
.B VT_SETMODE
.TQ
.B VT_GETSTATE
.TQ
.B VT_RELDISP
.TQ
.B VT_ACTIVATE
.TQ
.B VT_WAITACTIVE
.TQ
.B VT_DISALLOCATE
.TQ
.B VT_RESIZE
.TQ
.B VT_RESIZEX
See
.BR ioctl_vt (2).
.SH RETURN VALUE
On success, 0 is returned (except where indicated).
On failure, \-1 is returned, and
.I errno
is set to indicate the error.
.SH STANDARDS
Linux.
.SH CAVEATS
Do not regard this man page as documentation of the Linux console ioctls.
This is provided for the curious only, as an alternative to reading the
source.
Ioctl's are undocumented Linux internals, liable to be changed
without warning.
(And indeed, this page more or less describes the
situation as of kernel version 1.1.94;
there are many minor and not-so-minor
differences with earlier versions.)
.P
Very often, ioctls are introduced for communication between the
kernel and one particular well-known program (fdisk, hdparm, setserial,
tunelp, loadkeys, selection, setfont, etc.), and their behavior will be
changed when required by this particular program.
.SH SEE ALSO
.BR ioctl (2),
.BR TIOCLINUX (2const),
.BR ioctl_kd (2),
.BR ioctl_vt (2),
.BR dumpkeys (1),
.BR kbd_mode (1),
.BR loadkeys (1),
.BR mknod (1),
.BR setleds (1),
.BR setmetamode (1),
.BR execve (2),
.BR fcntl (2),
.BR ioctl_tty (2),
.BR ioperm (2),
.BR termios (3),
.BR console_codes (4),
.BR mt (4),
.BR sd (4),
.BR tty (4),
.BR ttyS (4),
.BR vcs (4),
.BR vcsa (4),
.BR charsets (7),
.BR mapscrn (8),
.BR resizecons (8),
.BR setfont (8)
