'\" t
.\" Copyright (C) 2007 Michael Kerrisk <mtk.manpages@gmail.com>
.\" with some input from Stepan Kasal <kasal@ucw.cz>
.\"
.\" Some content retained from an earlier version of this page:
.\" Copyright (C) 1998 Andries Brouwer (aeb@cwi.nl)
.\" Modifications for 2.2 and 2.4 Copyright (C) 2002 Ian Redfern
.\" <redferni@logica.com>
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.TH syscalls 2 (date) "Linux man-pages (unreleased)"
.SH NAME
syscalls \- Linux system calls
.SH SYNOPSIS
.nf
Linux system calls.
.fi
.SH DESCRIPTION
The system call is the fundamental interface between an application
and the Linux kernel.
.SS System calls and library wrapper functions
System calls are generally not invoked directly,
but rather via wrapper functions in glibc (or perhaps some other library).
For details of direct invocation of a system call, see
.BR intro (2).
Often, but not always, the name of the wrapper function is the same
as the name of the system call that it invokes.
For example, glibc contains a function
.BR chdir ()
which invokes the underlying "chdir" system call.
.P
Often the glibc wrapper function is quite thin, doing little work
other than copying arguments to the right registers
before invoking the system call,
and then setting
.I errno
appropriately after the system call has returned.
(These are the same steps that are performed by
.BR syscall (2),
which can be used to invoke system calls
for which no wrapper function is provided.)
Note: system calls indicate a failure by returning a negative error
number to the caller on architectures without a separate error register/flag,
as noted in
.BR syscall (2);
when this happens,
the wrapper function negates the returned error number
(to make it positive), copies it to
.IR errno ,
and returns \-1 to the caller of the wrapper.
.P
Sometimes, however, the wrapper function does some extra work
before invoking the system call.
For example, nowadays there are (for reasons described below) two
related system calls,
.BR truncate (2)
and
.BR truncate64 (2),
and the glibc
.BR truncate ()
wrapper function checks which of those system calls
are provided by the kernel and determines which should be employed.
.SS System call list
Below is a list of the Linux system calls.
In the list, the
.I Kernel
column indicates the kernel version
for those system calls that were new in Linux 2.2,
or have appeared since that kernel version.
Note the following points:
.IP \[bu] 3
Where no kernel version is indicated,
the system call appeared in Linux 1.0 or earlier.
.IP \[bu]
Where a system call is marked "1.2"
this means the system call probably appeared in a Linux 1.1.x kernel version,
and first appeared in a stable kernel with 1.2.
(Development of the Linux 1.2 kernel was initiated from a branch of
Linux 1.0.6 via the Linux 1.1.x unstable kernel series.)
.IP \[bu]
Where a system call is marked "2.0"
this means the system call probably appeared in a Linux 1.3.x kernel version,
and first appeared in a stable kernel with Linux 2.0.
(Development of the Linux 2.0 kernel was initiated from a branch of
Linux 1.2.x, somewhere around Linux 1.2.10,
via the Linux 1.3.x unstable kernel series.)
.\" Was Linux 2.0 started from a branch of Linux 1.2.10?
.\" At least from the timestamps of the tarballs of
.\" of Linux 1.2.10 and Linux 1.3.0, that's how it looks, but in
.\" fact the diff doesn't seem very clear, the
.\" Linux 1.3.0 .tar.bz is much bigger (2.0 MB) than the
.\" Linux 1.2.10 .tar.bz2 (1.8 MB), and AEB points out the
.\" timestamps of some files in Linux 1.3.0 seem to be older
.\" than those in Linux 1.2.10.  All of this suggests
.\" that there might not have been a clean branch point.
.IP \[bu]
Where a system call is marked "2.2"
this means the system call probably appeared in a Linux 2.1.x kernel version,
and first appeared in a stable kernel with Linux 2.2.0.
(Development of the Linux 2.2 kernel was initiated from a branch of
Linux 2.0.21 via the Linux 2.1.x unstable kernel series.)
.IP \[bu]
Where a system call is marked "2.4"
this means the system call probably appeared in a Linux 2.3.x kernel version,
and first appeared in a stable kernel with Linux 2.4.0.
(Development of the Linux 2.4 kernel was initiated from a branch of
Linux 2.2.8 via the Linux 2.3.x unstable kernel series.)
.IP \[bu]
Where a system call is marked "2.6"
this means the system call probably appeared in a Linux 2.5.x kernel version,
and first appeared in a stable kernel with Linux 2.6.0.
(Development of Linux 2.6 was initiated from a branch
of Linux 2.4.15 via the Linux 2.5.x unstable kernel series.)
.IP \[bu]
Starting with Linux 2.6.0, the development model changed,
and new system calls may appear in each Linux 2.6.x release.
In this case, the exact version number where the system call appeared
is shown.
This convention continues with the Linux 3.x kernel series,
which followed on from Linux 2.6.39; and the Linux 4.x kernel series,
which followed on from Linux 3.19; and the Linux 5.x kernel series,
which followed on from Linux 4.20; and the Linux 6.x kernel series,
which followed on from Linux 5.19.
.IP \[bu]
In some cases, a system call was added to a stable kernel
series after it branched from the previous stable kernel
series, and then backported into the earlier stable kernel series.
For example some system calls that appeared in Linux 2.6.x were also backported
into a Linux 2.4.x release after Linux 2.4.15.
When this is so, the version where the system call appeared
in both of the major kernel series is listed.
.P
The list of system calls that are available as at Linux 5.14
(or in a few cases only on older kernels) is as follows:
.P
.\"
.\" Looking at scripts/checksyscalls.sh in the kernel source is
.\" instructive about x86 specifics.
.\"
.TS
Lb       Lb Lb
Lw(26n)2 L  Lx.
System call	Kernel	Notes
_
\f[B]_llseek\f[](2)	1.2
\f[B]_newselect\f[](2)	2.0
\f[B]_sysctl\f[](2)	2.0	Removed in 5.5
T{
.BR accept (2)
T}	2.0	T{
See notes on \f[B]socketcall\f[](2)
T}
\f[B]accept4\f[](2)	2.6.28
\f[B]access\f[](2)	1.0
\f[B]acct\f[](2)	1.0
\f[B]add_key\f[](2)	2.6.10
\f[B]adjtimex\f[](2)	1.0
\f[B]alarm\f[](2)	1.0
\f[B]alloc_hugepages\f[](2)	2.5.36	Removed in 2.5.44
.\" 4adeefe161a74369e44cc8e663f240ece0470dc3
\f[B]arc_gettls\f[](2)	3.9	ARC only
\f[B]arc_settls\f[](2)	3.9	ARC only
.\" 91e040a79df73d371f70792f30380d4e44805250
\f[B]arc_usr_cmpxchg\f[](2)	4.9	ARC only
.\" x86: 79170fda313ed5be2394f87aa2a00d597f8ed4a1
T{
.BR arch_prctl (2)
T}	2.6	T{
x86_64, x86 since 4.12
T}
.\" 9674cdc74d63f346870943ef966a034f8c71ee57
\f[B]atomic_barrier\f[](2)	2.6.34	m68k only
\f[B]atomic_cmpxchg_32\f[](2)	2.6.34	m68k only
T{
.BR bdflush (2)
T}	1.2	T{
Deprecated (does nothing)
since 2.6,
removed in 5.15
T}
T{
.BR bind (2)
T}	2.0	T{
See notes on \f[B]socketcall\f[](2)
T}
\f[B]bpf\f[](2)	3.18
\f[B]brk\f[](2)	1.0
T{
.BR breakpoint (2)
T}	2.2	T{
ARM OABI only, defined with
\f[B]__ARM_NR\f[] prefix
T}
\f[B]cacheflush\f[](2)	1.2	Not on x86
\f[B]capget\f[](2)	2.2
\f[B]capset\f[](2)	2.2
\f[B]chdir\f[](2)	1.0
\f[B]chmod\f[](2)	1.0
T{
.BR chown (2)
T}	2.2	T{
See
.BR chown (2)
for
version details
T}
\f[B]chown32\f[](2)	2.4
\f[B]chroot\f[](2)	1.0
\f[B]clock_adjtime\f[](2)	2.6.39
\f[B]clock_getres\f[](2)	2.6
\f[B]clock_gettime\f[](2)	2.6
\f[B]clock_nanosleep\f[](2)	2.6
\f[B]clock_settime\f[](2)	2.6
\f[B]clone2\f[](2)	2.4	IA-64 only
\f[B]clone\f[](2)	1.0
\f[B]clone3\f[](2)	5.3
\f[B]close\f[](2)	1.0
\f[B]close_range\f[](2)	5.9
.\" .\" dcef1f634657dabe7905af3ccda12cf7f0b6fcc1
.\" .\" cc20d42986d5807cbe4f5c7c8e3dab2e59ea0db3
.\" .\" db695c0509d6ec9046ee5e4c520a19fa17d9fce2
.\" \f[B]cmpxchg\f[](2)	2.6.12	T{
.\" ARM, syscall constant never was
.\" exposed to user space, in-kernel
.\" definition had \f[B]__ARM_NR\f[] prefix,
.\" removed in 4.4
.\" T}
.\" 867e359b97c970a60626d5d76bbe2a8fadbf38fb
.\" bb9d812643d8a121df7d614a2b9c60193a92deb0
T{
.BR connect (2)
T}	2.0	T{
See notes on \f[B]socketcall\f[](2)
T}
\f[B]copy_file_range\f[](2)	4.5
\f[B]creat\f[](2)	1.0
\f[B]create_module\f[](2)	1.0	Removed in 2.6
\f[B]delete_module\f[](2)	1.0
.\" 1394f03221790a988afc3e4b3cb79f2e477246a9
.\" 4ba66a9760722ccbb691b8f7116cad2f791cca7b
\f[B]dup\f[](2)	1.0
\f[B]dup2\f[](2)	1.0
\f[B]dup3\f[](2)	2.6.27
\f[B]epoll_create\f[](2)	2.6
\f[B]epoll_create1\f[](2)	2.6.27
\f[B]epoll_ctl\f[](2)	2.6
\f[B]epoll_pwait\f[](2)	2.6.19
\f[B]epoll_pwait2\f[](2)	5.11
\f[B]epoll_wait\f[](2)	2.6
\f[B]eventfd\f[](2)	2.6.22
\f[B]eventfd2\f[](2)	2.6.27
T{
.BR execv (2)
T}	2.0	T{
SPARC/SPARC64 only, for
compatibility with SunOS
T}
\f[B]execve\f[](2)	1.0
\f[B]execveat\f[](2)	3.19
\f[B]exit\f[](2)	1.0
\f[B]exit_group\f[](2)	2.6
\f[B]faccessat\f[](2)	2.6.16
\f[B]faccessat2\f[](2)	5.8
\f[B]fadvise64\f[](2)	2.6
.\" Implements \f[B]posix_fadvise\f[](2)
\f[B]fadvise64_64\f[](2)	2.6
\f[B]fallocate\f[](2)	2.6.23
\f[B]fanotify_init\f[](2)	2.6.37
\f[B]fanotify_mark\f[](2)	2.6.37
.\" The fanotify calls were added in Linux 2.6.36,
.\" but disabled while the API was finalized.
\f[B]fchdir\f[](2)	1.0
\f[B]fchmod\f[](2)	1.0
\f[B]fchmodat\f[](2)	2.6.16
\f[B]fchown\f[](2)	1.0
\f[B]fchown32\f[](2)	2.4
\f[B]fchownat\f[](2)	2.6.16
\f[B]fcntl\f[](2)	1.0
\f[B]fcntl64\f[](2)	2.4
\f[B]fdatasync\f[](2)	2.0
\f[B]fgetxattr\f[](2)	2.6; 2.4.18
\f[B]finit_module\f[](2)	3.8
\f[B]flistxattr\f[](2)	2.6; 2.4.18
\f[B]flock\f[](2)	2.0
\f[B]fork\f[](2)	1.0
\f[B]free_hugepages\f[](2)	2.5.36	Removed in 2.5.44
\f[B]fremovexattr\f[](2)	2.6; 2.4.18
\f[B]fsconfig\f[](2)	5.2
\f[B]fsetxattr\f[](2)	2.6; 2.4.18
\f[B]fsmount\f[](2)	5.2
\f[B]fsopen\f[](2)	5.2
\f[B]fspick\f[](2)	5.2
\f[B]fstat\f[](2)	1.0
\f[B]fstat64\f[](2)	2.4
\f[B]fstatat64\f[](2)	2.6.16
\f[B]fstatfs\f[](2)	1.0
\f[B]fstatfs64\f[](2)	2.6
\f[B]fsync\f[](2)	1.0
\f[B]ftruncate\f[](2)	1.0
\f[B]ftruncate64\f[](2)	2.4
\f[B]futex\f[](2)	2.6
\f[B]futimesat\f[](2)	2.6.16
\f[B]get_kernel_syms\f[](2)	1.0	Removed in 2.6
\f[B]get_mempolicy\f[](2)	2.6.6
\f[B]get_robust_list\f[](2)	2.6.17
\f[B]get_thread_area\f[](2)	2.6
.\" 8fcd6c45f5a65621ec809b7866a3623e9a01d4ed
T{
.BR get_tls (2)
T}	4.15	T{
ARM OABI only, has
\f[B]__ARM_NR\f[] prefix
T}
\f[B]getcpu\f[](2)	2.6.19
\f[B]getcwd\f[](2)	2.2
\f[B]getdents\f[](2)	2.0
\f[B]getdents64\f[](2)	2.4
.\" parisc: 863722e856e64dae0e252b6bb546737c6c5626ce
T{
.BR getdomainname (2)
T}	2.2	T{
SPARC, SPARC64; available
as \f[B]osf_getdomainname\f[](2)
on Alpha since Linux 2.0
T}
.\" ec98c6b9b47df6df1c1fa6cf3d427414f8c2cf16
T{
.BR getdtablesize (2)
T}	2.0	T{
SPARC (removed in 2.6.26),
available on Alpha as
\f[B]osf_getdtablesize\f[](2)
T}
\f[B]getegid\f[](2)	1.0
\f[B]getegid32\f[](2)	2.4
\f[B]geteuid\f[](2)	1.0
\f[B]geteuid32\f[](2)	2.4
\f[B]getgid\f[](2)	1.0
\f[B]getgid32\f[](2)	2.4
\f[B]getgroups\f[](2)	1.0
\f[B]getgroups32\f[](2)	2.4
.\" SPARC removal: ec98c6b9b47df6df1c1fa6cf3d427414f8c2cf16
T{
.BR gethostname (2)
T}	2.0	T{
Alpha, was available on
SPARC up to Linux 2.6.26
T}
\f[B]getitimer\f[](2)	1.0
T{
.BR getpeername (2)
T}	2.0	T{
See notes on \f[B]socketcall\f[](2)
T}
T{
.BR getpagesize (2)
T}	2.0	T{
Alpha, SPARC/SPARC64 only
T}
\f[B]getpgid\f[](2)	1.0
\f[B]getpgrp\f[](2)	1.0
\f[B]getpid\f[](2)	1.0
\f[B]getppid\f[](2)	1.0
\f[B]getpriority\f[](2)	1.0
\f[B]getrandom\f[](2)	3.17
\f[B]getresgid\f[](2)	2.2
\f[B]getresgid32\f[](2)	2.4
\f[B]getresuid\f[](2)	2.2
\f[B]getresuid32\f[](2)	2.4
\f[B]getrlimit\f[](2)	1.0
\f[B]getrusage\f[](2)	1.0
\f[B]getsid\f[](2)	2.0
T{
.BR getsockname (2)
T}	2.0	T{
See notes on \f[B]socketcall\f[](2)
T}
T{
.BR getsockopt (2)
T}	2.0	T{
See notes on \f[B]socketcall\f[](2)
T}
\f[B]gettid\f[](2)	2.4.11
\f[B]gettimeofday\f[](2)	1.0
\f[B]getuid\f[](2)	1.0
\f[B]getuid32\f[](2)	2.4
T{
.BR getunwind (2)
T}	2.4.8	T{
IA-64 only; deprecated
T}
\f[B]getxattr\f[](2)	2.6; 2.4.18
T{
.BR getxgid (2)
T}	2.0	T{
Alpha only; see NOTES
T}
T{
.BR getxpid (2)
T}	2.0	T{
Alpha only; see NOTES
T}
T{
.BR getxuid (2)
T}	2.0	T{
Alpha only; see NOTES
T}
\f[B]init_module\f[](2)	1.0
\f[B]inotify_add_watch\f[](2)	2.6.13
\f[B]inotify_init\f[](2)	2.6.13
\f[B]inotify_init1\f[](2)	2.6.27
\f[B]inotify_rm_watch\f[](2)	2.6.13
\f[B]io_cancel\f[](2)	2.6
\f[B]io_destroy\f[](2)	2.6
\f[B]io_getevents\f[](2)	2.6
\f[B]io_pgetevents\f[](2)	4.18
\f[B]io_setup\f[](2)	2.6
\f[B]io_submit\f[](2)	2.6
\f[B]io_uring_enter\f[](2)	5.1
\f[B]io_uring_register\f[](2)	5.1
\f[B]io_uring_setup\f[](2)	5.1
\f[B]ioctl\f[](2)	1.0
\f[B]ioperm\f[](2)	1.0
\f[B]iopl\f[](2)	1.0
\f[B]ioprio_get\f[](2)	2.6.13
\f[B]ioprio_set\f[](2)	2.6.13
\f[B]ipc\f[](2)	1.0
.\" Implements System V IPC calls
\f[B]kcmp\f[](2)	3.5
\f[B]kern_features\f[](2)	3.7	SPARC64 only
.\" FIXME . document kern_features():
.\" commit 517ffce4e1a03aea979fe3a18a3dd1761a24fafb
\f[B]kexec_file_load\f[](2)	3.17
\f[B]kexec_load\f[](2)	2.6.13
.\" The entry in the syscall table was reserved starting in 2.6.7
.\" Was named sys_kexec_load() from 2.6.7 to 2.6.16
\f[B]keyctl\f[](2)	2.6.10
\f[B]kill\f[](2)	1.0
\f[B]landlock_add_rule\f[](2)	5.13
\f[B]landlock_create_ruleset\f[](2)	5.13
\f[B]landlock_restrict_self\f[](2)	5.13
T{
.BR lchown (2)
T}	1.0	T{
See
.BR chown (2)
for
version details
T}
\f[B]lchown32\f[](2)	2.4
\f[B]lgetxattr\f[](2)	2.6; 2.4.18
\f[B]link\f[](2)	1.0
\f[B]linkat\f[](2)	2.6.16
T{
.BR listen (2)
T}	2.0	T{
See notes on \f[B]socketcall\f[](2)
T}
\f[B]listxattr\f[](2)	2.6; 2.4.18
\f[B]llistxattr\f[](2)	2.6; 2.4.18
\f[B]lookup_dcookie\f[](2)	2.6
\f[B]lremovexattr\f[](2)	2.6; 2.4.18
\f[B]lseek\f[](2)	1.0
\f[B]lsetxattr\f[](2)	2.6; 2.4.18
\f[B]lstat\f[](2)	1.0
\f[B]lstat64\f[](2)	2.4
\f[B]madvise\f[](2)	2.4
\f[B]mbind\f[](2)	2.6.6
\f[B]memory_ordering\f[](2)	2.2	SPARC64 only
.\" 26025bbfbba33a9425be1b89eccb4664ea4c17b6
.\" bb6fb6dfcc17cddac11ac295861f7608194447a7
\f[B]membarrier\f[](2)	3.17
\f[B]memfd_create\f[](2)	3.17
\f[B]memfd_secret\f[](2)	5.14
\f[B]migrate_pages\f[](2)	2.6.16
\f[B]mincore\f[](2)	2.4
\f[B]mkdir\f[](2)	1.0
\f[B]mkdirat\f[](2)	2.6.16
\f[B]mknod\f[](2)	1.0
\f[B]mknodat\f[](2)	2.6.16
\f[B]mlock\f[](2)	2.0
\f[B]mlock2\f[](2)	4.4
\f[B]mlockall\f[](2)	2.0
\f[B]mmap\f[](2)	1.0
\f[B]mmap2\f[](2)	2.4
\f[B]modify_ldt\f[](2)	1.0
\f[B]mount\f[](2)	1.0
\f[B]move_mount\f[](2)	5.2
\f[B]move_pages\f[](2)	2.6.18
\f[B]mprotect\f[](2)	1.0
\f[B]mq_getsetattr\f[](2)	2.6.6
.\" Implements \f[B]mq_getattr\f[](3) and \f[B]mq_setattr\f[](3)
\f[B]mq_notify\f[](2)	2.6.6
\f[B]mq_open\f[](2)	2.6.6
\f[B]mq_timedreceive\f[](2)	2.6.6
\f[B]mq_timedsend\f[](2)	2.6.6
\f[B]mq_unlink\f[](2)	2.6.6
\f[B]mremap\f[](2)	2.0
T{
.BR msgctl (2)
T}	2.0	T{
See notes on \f[B]ipc\f[](2)
T}
T{
.BR msgget (2)
T}	2.0	T{
See notes on \f[B]ipc\f[](2)
T}
T{
.BR msgrcv (2)
T}	2.0	T{
See notes on \f[B]ipc\f[](2)
T}
T{
.BR msgsnd (2)
T}	2.0	T{
See notes on \f[B]ipc\f[](2)
T}
\f[B]msync\f[](2)	2.0
.\" \f[B]multiplexer\f[](2)	??	__NR_multiplexer reserved on
.\"		PowerPC, but unimplemented?
\f[B]munlock\f[](2)	2.0
\f[B]munlockall\f[](2)	2.0
\f[B]munmap\f[](2)	1.0
\f[B]name_to_handle_at\f[](2)	2.6.39
\f[B]nanosleep\f[](2)	2.0
.\" 5590ff0d5528b60153c0b4e7b771472b5a95e297
T{
.BR newfstatat (2)
T}	2.6.16	T{
See \f[B]stat\f[](2)
T}
\f[B]nfsservctl\f[](2)	2.2	Removed in 3.1
\f[B]nice\f[](2)	1.0
T{
.BR old_adjtimex (2)
T}	2.0	T{
Alpha only; see NOTES
T}
T{
.BR old_getrlimit (2)
T}	2.4	T{
Old variant of \f[B]getrlimit\f[](2)
that used a different value
for \f[B]RLIM_INFINITY\f[]
T}
\f[B]oldfstat\f[](2)	1.0
\f[B]oldlstat\f[](2)	1.0
\f[B]oldolduname\f[](2)	1.0
\f[B]oldstat\f[](2)	1.0
T{
.BR oldumount (2)
T}	2.4.116	T{
Name of the old \f[B]umount\f[](2)
syscall on Alpha
T}
\f[B]olduname\f[](2)	1.0
\f[B]open\f[](2)	1.0
\f[B]open_by_handle_at\f[](2)	2.6.39
\f[B]open_tree\f[](2)	5.2
\f[B]openat\f[](2)	2.6.16
\f[B]openat2\f[](2)	5.6
.\" 9d02a4283e9ce4e9ca11ff00615bdacdb0515a1a
T{
.BR or1k_atomic (2)
T}	3.1	T{
OpenRISC 1000 only
T}
\f[B]pause\f[](2)	1.0
\f[B]pciconfig_iobase\f[](2)	2.2.15; 2.4	Not on x86
.\" Alpha, PowerPC, ARM; not x86
\f[B]pciconfig_read\f[](2)	2.0.26; 2.2	Not on x86
.\" , PowerPC, ARM; not x86
\f[B]pciconfig_write\f[](2)	2.0.26; 2.2	Not on x86
.\" , PowerPC, ARM; not x86
T{
.BR perf_event_open (2)
T}	2.6.31	T{
Was perf_counter_open() in
2.6.31; renamed in 2.6.32
T}
\f[B]personality\f[](2)	1.2
T{
.BR perfctr (2)
T}	2.2	T{
SPARC only; removed in 2.6.34
T}
.\"	commit c7d5a0050773e98d1094eaa9f2a1a793fafac300 removed perfctr()
\f[B]perfmonctl\f[](2)	2.4	IA-64 only; removed in 5.10
\f[B]pidfd_getfd\f[](2)	5.6
\f[B]pidfd_send_signal\f[](2)	5.1
\f[B]pidfd_open\f[](2)	5.3
\f[B]pipe\f[](2)	1.0
\f[B]pipe2\f[](2)	2.6.27
\f[B]pivot_root\f[](2)	2.4
\f[B]pkey_alloc\f[](2)	4.8
\f[B]pkey_free\f[](2)	4.8
\f[B]pkey_mprotect\f[](2)	4.8
\f[B]poll\f[](2)	2.0.36; 2.2
\f[B]ppoll\f[](2)	2.6.16
\f[B]prctl\f[](2)	2.2
T{
.BR pread64 (2)
T}		T{
Added as "pread" in 2.2;
renamed "pread64" in 2.6
T}
\f[B]preadv\f[](2)	2.6.30
\f[B]preadv2\f[](2)	4.6
\f[B]prlimit64\f[](2)	2.6.36
\f[B]process_madvise\f[](2)	5.10
\f[B]process_vm_readv\f[](2)	3.2
\f[B]process_vm_writev\f[](2)	3.2
\f[B]pselect6\f[](2)	2.6.16
.\" Implements \f[B]pselect\f[](2)
\f[B]ptrace\f[](2)	1.0
T{
.BR pwrite64 (2)
T}		T{
Added as "pwrite" in 2.2;
renamed "pwrite64" in 2.6
T}
\f[B]pwritev\f[](2)	2.6.30
\f[B]pwritev2\f[](2)	4.6
\f[B]query_module\f[](2)	2.2	Removed in 2.6
\f[B]quotactl\f[](2)	1.0
\f[B]quotactl_fd\f[](2)	5.14
\f[B]read\f[](2)	1.0
\f[B]readahead\f[](2)	2.4.13
\f[B]readdir\f[](2)	1.0
.\" Supersedes \f[B]getdents\f[](2)
\f[B]readlink\f[](2)	1.0
\f[B]readlinkat\f[](2)	2.6.16
\f[B]readv\f[](2)	2.0
\f[B]reboot\f[](2)	1.0
T{
.BR recv (2)
T}	2.0	T{
See notes on \f[B]socketcall\f[](2)
T}
T{
.BR recvfrom (2)
T}	2.0	T{
See notes on \f[B]socketcall\f[](2)
T}
T{
.BR recvmsg (2)
T}	2.0	T{
See notes on \f[B]socketcall\f[](2)
T}
\f[B]recvmmsg\f[](2)	2.6.33
T{
.BR remap_file_pages (2)
T}	2.6	T{
Deprecated since 3.16
T}
\f[B]removexattr\f[](2)	2.6; 2.4.18
\f[B]rename\f[](2)	1.0
\f[B]renameat\f[](2)	2.6.16
\f[B]renameat2\f[](2)	3.15
\f[B]request_key\f[](2)	2.6.10
\f[B]restart_syscall\f[](2)	2.6
.\" 921ebd8f2c081b3cf6c3b29ef4103eef3ff26054
\f[B]riscv_flush_icache\f[](2)	4.15	RISC-V only
\f[B]rmdir\f[](2)	1.0
\f[B]rseq\f[](2)	4.18
\f[B]rt_sigaction\f[](2)	2.2
\f[B]rt_sigpending\f[](2)	2.2
\f[B]rt_sigprocmask\f[](2)	2.2
\f[B]rt_sigqueueinfo\f[](2)	2.2
\f[B]rt_sigreturn\f[](2)	2.2
\f[B]rt_sigsuspend\f[](2)	2.2
\f[B]rt_sigtimedwait\f[](2)	2.2
\f[B]rt_tgsigqueueinfo\f[](2)	2.6.31
T{
.BR rtas (2)
T}	2.6.2	T{
PowerPC/PowerPC64 only
T}
\f[B]s390_runtime_instr\f[](2)	3.7	s390 only
\f[B]s390_pci_mmio_read\f[](2)	3.19	s390 only
\f[B]s390_pci_mmio_write\f[](2)	3.19	s390 only
\f[B]s390_sthyi\f[](2)	4.15	s390 only
\f[B]s390_guarded_storage\f[](2)	4.12	s390 only
T{
.BR sched_get_affinity (2)
T}	2.6	T{
Name of
.BR \%sched_getaffinity (2)
on SPARC and SPARC64
T}
\f[B]sched_get_priority_max\f[](2)	2.0
\f[B]sched_get_priority_min\f[](2)	2.0
\f[B]sched_getaffinity\f[](2)	2.6
\f[B]sched_getattr\f[](2)	3.14
\f[B]sched_getparam\f[](2)	2.0
\f[B]sched_getscheduler\f[](2)	2.0
\f[B]sched_rr_get_interval\f[](2)	2.0
T{
.BR sched_set_affinity (2)
T}	2.6	T{
Name of
.BR \%sched_setaffinity (2)
on SPARC and SPARC64
T}
\f[B]sched_setaffinity\f[](2)	2.6
\f[B]sched_setattr\f[](2)	3.14
\f[B]sched_setparam\f[](2)	2.0
\f[B]sched_setscheduler\f[](2)	2.0
\f[B]sched_yield\f[](2)	2.0
\f[B]seccomp\f[](2)	3.17
\f[B]select\f[](2)	1.0
T{
.BR semctl (2)
T}	2.0	T{
See notes on \f[B]ipc\f[](2)
T}
T{
.BR semget (2)
T}	2.0	T{
See notes on \f[B]ipc\f[](2)
T}
T{
.BR semop (2)
T}	2.0	T{
See notes on \f[B]ipc\f[](2)
T}
\f[B]semtimedop\f[](2)	2.6; 2.4.22
T{
.BR send (2)
T}	2.0	T{
See notes on \f[B]socketcall\f[](2)
T}
\f[B]sendfile\f[](2)	2.2
\f[B]sendfile64\f[](2)	2.6; 2.4.19
\f[B]sendmmsg\f[](2)	3.0
T{
.BR sendmsg (2)
T}	2.0	T{
See notes on \f[B]socketcall\f[](2)
T}
T{
.BR sendto (2)
T}	2.0	T{
See notes on \f[B]socketcall\f[](2)
T}
\f[B]set_mempolicy\f[](2)	2.6.6
\f[B]set_robust_list\f[](2)	2.6.17
\f[B]set_thread_area\f[](2)	2.6
\f[B]set_tid_address\f[](2)	2.6
T{
.BR set_tls (2)
T}	2.6.11	T{
ARM OABI/EABI only (constant
has \f[B]__ARM_NR\f[] prefix)
T}
.\" \f[B]setaltroot\f[](2)	2.6.10	T{
.\" Removed in 2.6.11, exposed one
.\" of implementation details of
.\" \f[B]personality\f[](2) (creating an
.\" alternative root, precursor of
.\" mount namespaces) to user space.
.\" T}
.\" See http://lkml.org/lkml/2005/8/1/83
.\" "[PATCH] remove sys_set_zone_reclaim()"
\f[B]setdomainname\f[](2)	1.0
\f[B]setfsgid\f[](2)	1.2
\f[B]setfsgid32\f[](2)	2.4
\f[B]setfsuid\f[](2)	1.2
\f[B]setfsuid32\f[](2)	2.4
\f[B]setgid\f[](2)	1.0
\f[B]setgid32\f[](2)	2.4
\f[B]setgroups\f[](2)	1.0
\f[B]setgroups32\f[](2)	2.4
.\" arch/alpha/include/asm/core_lca.h
T{
.BR sethae (2)
T}	2.0	T{
Alpha only; see NOTES
T}
\f[B]sethostname\f[](2)	1.0
\f[B]setitimer\f[](2)	1.0
\f[B]setns\f[](2)	3.0
\f[B]setpgid\f[](2)	1.0
T{
.BR setpgrp (2)
T}	2.0	T{
Alternative name for
.BR setpgid (2)
on Alpha
T}
\f[B]setpriority\f[](2)	1.0
\f[B]setregid\f[](2)	1.0
\f[B]setregid32\f[](2)	2.4
\f[B]setresgid\f[](2)	2.2
\f[B]setresgid32\f[](2)	2.4
\f[B]setresuid\f[](2)	2.2
\f[B]setresuid32\f[](2)	2.4
\f[B]setreuid\f[](2)	1.0
\f[B]setreuid32\f[](2)	2.4
\f[B]setrlimit\f[](2)	1.0
\f[B]setsid\f[](2)	1.0
T{
.BR setsockopt (2)
T}	2.0	T{
See notes on \f[B]socketcall\f[](2)
T}
\f[B]settimeofday\f[](2)	1.0
\f[B]setuid\f[](2)	1.0
\f[B]setuid32\f[](2)	2.4
\f[B]setup\f[](2)	1.0	Removed in 2.2
\f[B]setxattr\f[](2)	2.6; 2.4.18
\f[B]sgetmask\f[](2)	1.0
T{
.BR shmat (2)
T}	2.0	T{
See notes on \f[B]ipc\f[](2)
T}
T{
.BR shmctl (2)
T}	2.0	T{
See notes on \f[B]ipc\f[](2)
T}
T{
.BR shmdt (2)
T}	2.0	T{
See notes on \f[B]ipc\f[](2)
T}
T{
.BR shmget (2)
T}	2.0	T{
See notes on \f[B]ipc\f[](2)
T}
T{
.BR shutdown (2)
T}	2.0	T{
See notes on \f[B]socketcall\f[](2)
T}
\f[B]sigaction\f[](2)	1.0
\f[B]sigaltstack\f[](2)	2.2
\f[B]signal\f[](2)	1.0
\f[B]signalfd\f[](2)	2.6.22
\f[B]signalfd4\f[](2)	2.6.27
\f[B]sigpending\f[](2)	1.0
\f[B]sigprocmask\f[](2)	1.0
\f[B]sigreturn\f[](2)	1.0
\f[B]sigsuspend\f[](2)	1.0
T{
.BR socket (2)
T}	2.0	T{
See notes on \f[B]socketcall\f[](2)
T}
\f[B]socketcall\f[](2)	1.0
.\" Implements BSD socket calls
T{
.BR socketpair (2)
T}	2.0	T{
See notes on \f[B]socketcall\f[](2)
T}
.\" 5a0015d62668e64c8b6e02e360fbbea121bfd5e6
\f[B]spill\f[](2)	2.6.13	Xtensa only
\f[B]splice\f[](2)	2.6.17
T{
.BR spu_create (2)
T}	2.6.16	T{
PowerPC/PowerPC64 only
T}
T{
.BR spu_run (2)
T}	2.6.16	T{
PowerPC/PowerPC64 only
T}
\f[B]ssetmask\f[](2)	1.0
\f[B]stat\f[](2)	1.0
\f[B]stat64\f[](2)	2.4
\f[B]statfs\f[](2)	1.0
\f[B]statfs64\f[](2)	2.6
\f[B]statx\f[](2)	4.11
\f[B]stime\f[](2)	1.0
T{
.BR subpage_prot (2)
T}	2.6.25	T{
PowerPC/PowerPC64 only
T}
T{
.BR swapcontext (2)
T}	2.6.3	T{
PowerPC/PowerPC64 only
T}
.\" 529d235a0e190ded1d21ccc80a73e625ebcad09b
\f[B]switch_endian\f[](2)	4.1	PowerPC64 only
\f[B]swapoff\f[](2)	1.0
\f[B]swapon\f[](2)	1.0
\f[B]symlink\f[](2)	1.0
\f[B]symlinkat\f[](2)	2.6.16
\f[B]sync\f[](2)	1.0
\f[B]sync_file_range\f[](2)	2.6.17
\f[B]sync_file_range2\f[](2)	2.6.22
.\" PowerPC, ARM, tile
.\" First appeared on ARM, as arm_sync_file_range(), but later renamed
.\" \f[B]sys_debug_setcontext\f[](2)	???	PowerPC if CONFIG_PPC32
\f[B]syncfs\f[](2)	2.6.39
\f[B]sys_debug_setcontext\f[](2)	2.6.11	PowerPC only
T{
.BR syscall (2)
T}	1.0	T{
Still available on ARM OABI
and MIPS O32 ABI
T}
\f[B]sysfs\f[](2)	1.2
\f[B]sysinfo\f[](2)	1.0
\f[B]syslog\f[](2)	1.0
.\" glibc interface is \f[B]klogctl\f[](3)
\f[B]sysmips\f[](2)	2.6.0	MIPS only
\f[B]tee\f[](2)	2.6.17
\f[B]tgkill\f[](2)	2.6
\f[B]time\f[](2)	1.0
\f[B]timer_create\f[](2)	2.6
\f[B]timer_delete\f[](2)	2.6
\f[B]timer_getoverrun\f[](2)	2.6
\f[B]timer_gettime\f[](2)	2.6
\f[B]timer_settime\f[](2)	2.6
.\" .\" b215e283992899650c4271e7385c79e26fb9a88e
.\" .\" 4d672e7ac79b5ec5cdc90e450823441e20464691
.\" \f[B]timerfd\f[](2)	2.6.22	T{
.\" Old timerfd interface,
.\" removed in 2.6.25
.\" T}
\f[B]timerfd_create\f[](2)	2.6.25
\f[B]timerfd_gettime\f[](2)	2.6.25
\f[B]timerfd_settime\f[](2)	2.6.25
\f[B]times\f[](2)	1.0
\f[B]tkill\f[](2)	2.6; 2.4.22
\f[B]truncate\f[](2)	1.0
\f[B]truncate64\f[](2)	2.4
\f[B]ugetrlimit\f[](2)	2.4
\f[B]umask\f[](2)	1.0
\f[B]umount\f[](2)	1.0
.\" sys_oldumount() -- __NR_umount
\f[B]umount2\f[](2)	2.2
.\" sys_umount() -- __NR_umount2
\f[B]uname\f[](2)	1.0
\f[B]unlink\f[](2)	1.0
\f[B]unlinkat\f[](2)	2.6.16
\f[B]unshare\f[](2)	2.6.16
\f[B]uselib\f[](2)	1.0
\f[B]ustat\f[](2)	1.0
\f[B]userfaultfd\f[](2)	4.3
\f[B]usr26\f[](2)	2.4.8.1	ARM OABI only
\f[B]usr32\f[](2)	2.4.8.1	ARM OABI only
\f[B]utime\f[](2)	1.0
\f[B]utimensat\f[](2)	2.6.22
\f[B]utimes\f[](2)	2.2
\f[B]utrap_install\f[](2)	2.2	SPARC64 only
.\" FIXME . document utrap_install()
.\" There's a man page for Solaris 5.11
\f[B]vfork\f[](2)	2.2
\f[B]vhangup\f[](2)	1.0
T{
.BR vm86old (2)
T}	1.0	T{
Was "vm86"; renamed in
2.0.28/2.2
T}
\f[B]vm86\f[](2)	2.0.28; 2.2
\f[B]vmsplice\f[](2)	2.6.17
\f[B]wait4\f[](2)	1.0
\f[B]waitid\f[](2)	2.6.10
\f[B]waitpid\f[](2)	1.0
\f[B]write\f[](2)	1.0
\f[B]writev\f[](2)	2.0
.\" 5a0015d62668e64c8b6e02e360fbbea121bfd5e6
\f[B]xtensa\f[](2)	2.6.13	Xtensa only
.TE
.P
On many platforms, including x86-32, socket calls are all multiplexed
(via glibc wrapper functions) through
.BR socketcall (2)
and similarly System\ V IPC calls are multiplexed through
.BR ipc (2).
.P
Although slots are reserved for them in the system call table,
the following system calls are not implemented in the standard kernel:
.BR afs_syscall (2), \" __NR_afs_syscall is 53 on Linux 2.6.22/i386
.BR break (2),       \" __NR_break is 17 on Linux 2.6.22/i386
.BR ftime (2),       \" __NR_ftime is 35 on Linux 2.6.22/i386
.BR getpmsg (2),     \" __NR_getpmsg is 188 on Linux 2.6.22/i386
.BR gtty (2),        \" __NR_gtty is 32 on Linux 2.6.22/i386
.BR idle (2),        \" __NR_idle is 112 on Linux 2.6.22/i386
.BR lock (2),        \" __NR_lock is 53 on Linux 2.6.22/i386
.BR madvise1 (2),    \" __NR_madvise1 is 219 on Linux 2.6.22/i386
.BR mpx (2),         \" __NR_mpx is 66 on Linux 2.6.22/i386
.BR phys (2),        \" Slot has been reused
.BR prof (2),        \" __NR_prof is 44 on Linux 2.6.22/i386
.BR profil (2),      \" __NR_profil is 98 on Linux 2.6.22/i386
.BR putpmsg (2),     \" __NR_putpmsg is 189 on Linux 2.6.22/i386
.\" __NR_security is 223 on Linux 2.4/i386; absent on 2.6/i386, present
.\" on a couple of 2.6 architectures
.BR security (2),    \" __NR_security is 223 on Linux 2.4/i386
.\" The security call is for future use.
.BR stty (2),        \" __NR_stty is 31 on Linux 2.6.22/i386
.BR tuxcall (2),     \" __NR_tuxcall is 184 on x86_64, also on PPC and alpha
.BR ulimit (2),      \" __NR_ulimit is 58 on Linux 2.6.22/i386
and
.BR vserver (2)      \" __NR_vserver is 273 on Linux 2.6.22/i386
(see also
.BR unimplemented (2)).
However,
.BR ftime (3),
.BR profil (3),
and
.BR ulimit (3)
exist as library routines.
The slot for
.BR phys (2)
is in use since Linux 2.1.116 for
.BR umount (2);
.BR phys (2)
will never be implemented.
The
.BR getpmsg (2)
and
.BR putpmsg (2)
calls are for kernels patched to support STREAMS,
and may never be in the standard kernel.
.P
There was briefly
.BR set_zone_reclaim (2),
added in Linux 2.6.13, and removed in Linux 2.6.16;
this system call was never available to user space.
.\"
.SS System calls on removed ports
Some system calls only ever existed on Linux architectures that have
since been removed from the kernel:
.TP
AVR32 (port removed in Linux 4.12)
.RS
.PD 0
.IP \[bu] 3
.BR pread (2)
.IP \[bu]
.BR pwrite (2)
.PD
.RE
.TP
Blackfin (port removed in Linux 4.17)
.RS
.PD 0
.IP \[bu] 3
.BR bfin_spinlock (2)
(added in Linux 2.6.22)
.IP \[bu]
.BR dma_memcpy (2)
(added in Linux 2.6.22)
.IP \[bu]
.BR pread (2)
(added in Linux 2.6.22)
.IP \[bu]
.BR pwrite (2)
(added in Linux 2.6.22)
.IP \[bu]
.BR sram_alloc (2)
(added in Linux 2.6.22)
.IP \[bu]
.BR sram_free (2)
(added in Linux 2.6.22)
.PD
.RE
.TP
Metag (port removed in Linux 4.17)
.RS
.PD 0
.IP \[bu] 3
.BR metag_get_tls (2)
(add in Linux 3.9)
.IP \[bu]
.BR metag_set_fpu_flags (2)
(add in Linux 3.9)
.IP \[bu]
.BR metag_set_tls (2)
(add in Linux 3.9)
.IP \[bu]
.BR metag_setglobalbit (2)
(add in Linux 3.9)
.PD
.RE
.TP
Tile (port removed in Linux 4.17)
.RS
.PD 0
.IP \[bu] 3
.BR cmpxchg_badaddr (2)
(added in Linux 2.6.36)
.PD
.RE
.SH NOTES
Roughly speaking, the code belonging to the system call
with number __NR_xxx defined in
.I /usr/include/asm/unistd.h
can be found in the Linux kernel source in the routine
.IR sys_xxx ().
There are many exceptions, however, mostly because
older system calls were superseded by newer ones,
and this has been treated somewhat unsystematically.
On platforms with
proprietary operating-system emulation,
such as sparc, sparc64, and alpha,
there are many additional system calls; mips64 also contains a full
set of 32-bit system calls.
.P
Over time, changes to the interfaces of some system calls have been
necessary.
One reason for such changes was the need to increase the size of
structures or scalar values passed to the system call.
Because of these changes, certain architectures
(notably, longstanding 32-bit architectures such as i386)
now have various groups of related system calls (e.g.,
.BR truncate (2)
and
.BR truncate64 (2))
which perform similar tasks, but which vary in
details such as the size of their arguments.
(As noted earlier, applications are generally unaware of this:
the glibc wrapper functions do some work to ensure that the right
system call is invoked, and that ABI compatibility is
preserved for old binaries.)
Examples of system calls that exist in multiple versions are
the following:
.IP \[bu] 3
By now there are three different versions of
.BR stat (2):
.IR sys_stat ()
(slot
.IR __NR_oldstat ),
.IR sys_newstat ()
(slot
.IR __NR_stat ),
and
.IR sys_stat64 ()
(slot
.IR __NR_stat64 ),
with the last being the most current.
.\" e.g., on 2.6.22/i386: __NR_oldstat 18, __NR_stat 106, __NR_stat64 195
.\" The stat system calls deal with three different data structures,
.\" defined in include/asm-i386/stat.h: __old_kernel_stat, stat, stat64
A similar story applies for
.BR lstat (2)
and
.BR fstat (2).
.IP \[bu]
Similarly, the defines
.IR __NR_oldolduname ,
.IR __NR_olduname ,
and
.I __NR_uname
refer to the routines
.IR sys_olduname (),
.IR sys_uname (),
and
.IR sys_newuname ().
.IP \[bu]
In Linux 2.0, a new version of
.BR vm86 (2)
appeared, with the old and the new kernel routines being named
.IR sys_vm86old ()
and
.IR sys_vm86 ().
.IP \[bu]
In Linux 2.4, a new version of
.BR getrlimit (2)
appeared, with the old and the new kernel routines being named
.IR sys_old_getrlimit ()
(slot
.IR __NR_getrlimit )
and
.IR sys_getrlimit ()
(slot
.IR __NR_ugetrlimit ).
.IP \[bu]
Linux 2.4 increased the size of user and group IDs from 16 to 32 bits.
.\" 64-bit off_t changes: ftruncate64, *stat64,
.\" fcntl64 (because of the flock structure), getdents64, *statfs64
To support this change, a range of system calls were added
(e.g.,
.BR chown32 (2),
.BR getuid32 (2),
.BR getgroups32 (2),
.BR setresuid32 (2)),
superseding earlier calls of the same name without the
"32" suffix.
.IP \[bu]
Linux 2.4 added support for applications on 32-bit architectures
to access large files (i.e., files for which the sizes and
file offsets can't be represented in 32 bits.)
To support this change, replacements were required for system calls
that deal with file offsets and sizes.
Thus the following system calls were added:
.BR fcntl64 (2),
.BR getdents64 (2),
.BR stat64 (2),
.BR statfs64 (2),
.BR truncate64 (2),
and their analogs that work with file descriptors or
symbolic links.
These system calls supersede the older system calls
which, except in the case of the "stat" calls,
have the same name without the "64" suffix.
.IP
On newer platforms that only have 64-bit file access and 32-bit UIDs/GIDs
(e.g., alpha, ia64, s390x, x86-64), there is just a single version of
the UID/GID and file access system calls.
On platforms (typically, 32-bit platforms) where the *64 and *32 calls exist,
the other versions are obsolete.
.IP \[bu]
The
.I rt_sig*
calls were added in Linux 2.2 to support the addition
of real-time signals (see
.BR signal (7)).
These system calls supersede the older system calls of the same
name without the "rt_" prefix.
.IP \[bu]
The
.BR select (2)
and
.BR mmap (2)
system calls use five or more arguments,
which caused problems in the way
argument passing on the i386 used to be set up.
Thus, while other architectures have
.IR sys_select ()
and
.IR sys_mmap ()
corresponding to
.I __NR_select
and
.IR __NR_mmap ,
on i386 one finds
.IR old_select ()
and
.IR old_mmap ()
(routines that use a pointer to an
argument block) instead.
These days passing five arguments
is not a problem any more, and there is a
.I __NR__newselect
.\" (used by libc 6)
that corresponds directly to
.IR sys_select ()
and similarly
.IR __NR_mmap2 .
s390x is the only 64-bit architecture that has
.IR old_mmap ().
.\" .P
.\" Two system call numbers,
.\" .IR __NR__llseek
.\" and
.\" .IR __NR__sysctl
.\" have an additional underscore absent in
.\" .IR sys_llseek ()
.\" and
.\" .IR sys_sysctl ().
.\"
.\" In Linux 2.1.81,
.\" .BR lchown (2)
.\" and
.\" .BR chown (2)
.\" were swapped; that is,
.\" .BR lchown (2)
.\" was added with the semantics that were then current for
.\" .BR chown (2),
.\" and the semantics of the latter call were changed to what
.\" they are today.
.\"
.\"
.SS "Architecture-specific details: Alpha"
.TP
.BR getxgid (2)
returns a pair of GID and effective GID via registers
.B r0
and
.BR r20 ;
it is provided
instead of
.BR getgid (2)
and
.BR getegid (2).
.TP
.BR getxpid (2)
returns a pair of PID and parent PID via registers
.B r0
and
.BR r20 ;
it is provided instead of
.BR getpid (2)
and
.BR getppid (2).
.TP
.BR old_adjtimex (2)
is a variant of
.BR adjtimex (2)
that uses
.IR "struct\ timeval32" ,
for compatibility with OSF/1.
.TP
.BR getxuid (2)
returns a pair of GID and effective GID via registers
.B r0
and
.BR r20 ;
it is provided instead of
.BR getuid (2)
and
.BR geteuid (2).
.TP
.BR sethae (2)
is used for configuring the Host Address Extension register on
low-cost Alphas in order to access address space beyond first 27 bits.
.SH SEE ALSO
.BR intro (2),
.BR syscall (2),
.BR unimplemented (2),
.BR errno (3),
.BR libc (7),
.BR vdso (7),
.BR ausyscall (8)
