.\" Copyright (C) Rivos Inc., 2024
.\"
.\" SPDX-License-Identifier: GPL-2.0-or-later
.\"
.TH __riscv_flush_icache 3 (date) "Linux man-pages (unreleased)"
.SH NAME
__riscv_flush_icache
\-
Flush icaches on RISC-V
.SH LIBRARY
Standard C library
.RI ( libc ,\~ \-lc )
.SH SYNOPSIS
.nf
.B #include <sys/cachectl.h>
.P
.B int __riscv_flush_icache(void *start, void *end, \
unsigned long flags);
.fi
.SH DESCRIPTION
.BR __riscv_flush_icache ()
enforces ordering between stores and instruction cache fetches.
.P
The range of addresses over which ordering is enforced is specified by
.I start
and
.IR end .
.P
The
.I flags
argument controls the extent of this ordering,
with the default behavior
(a
.I flags
value of 0)
being to enforce the fence on
all threads in the current process.
Setting the
.B SYS_RISCV_FLUSH_ICACHE_LOCAL
bit allows users to indicate that enforcing ordering on
only the current thread is necessary.
All other flag bits are reserved.
.SH STANDARDS
Linux on RISC-V.
.SH HISTORY
Linux 4.15.
glibc 2.27.
.SH SEE ALSO
.BR syscall (2)
