'\" t
.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Mon Mar 29 22:31:13 1993, David Metcalfe
.\" Modified Sun Jun  6 23:27:50 1993, David Metcalfe
.\" Modified Sat Jul 24 21:45:37 1993, Rik Faith (faith@cs.unc.edu)
.\" Modified Sat Dec 16 15:02:59 2000, Joseph S. Myers
.\"
.TH abs 3 (date) "Linux man-pages (unreleased)"
.SH NAME
abs, labs, llabs, imaxabs,
uabs, ulabs, ullabs, uimaxabs
\-
compute the absolute value of an integer
.SH LIBRARY
Standard C library
.RI ( libc ,\~ \-lc )
.SH SYNOPSIS
.nf
.B #include <stdlib.h>
.P
.BI "int abs(int " j );
.BI "long labs(long " j );
.BI "long long llabs(long long " j );
.P
.BI "unsigned int uabs(int " j );
.BI "unsigned long ulabs(long " j );
.BI "unsigned long long ullabs(long long " j );
.P
.B #include <inttypes.h>
.P
.BI "intmax_t imaxabs(intmax_t " j );
.BI "uintmax_t uimaxabs(intmax_t " j );
.fi
.P
.RS -4
Feature Test Macro Requirements for glibc (see
.BR feature_test_macros (7)):
.RE
.P
.BR llabs ():
.nf
    _ISOC99_SOURCE || _POSIX_C_SOURCE >= 200112L
.fi
.P
.BR uabs (),
.BR ulabs (),
.BR ullabs (),
.BR uimaxabs ():
.nf
    _ISOC2Y_SOURCE
.fi
.SH DESCRIPTION
These functions
compute the absolute value of the argument
.I j
of the
appropriate integer type for the function.
.SH RETURN VALUE
Returns the absolute value of the integer argument,
of the appropriate integer type for the function.
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lbx lb lb
l l l.
Interface	Attribute	Value
T{
.na
.nh
.BR abs (),
.BR labs (),
.BR llabs (),
.BR imaxabs (),
.BR uabs (),
.BR ulabs (),
.BR \%ullabs (),
.BR \%uimaxabs ()
T}	Thread safety	MT-Safe
.TE
.SH STANDARDS
.TP
.BR abs ()
.TQ
.BR labs ()
.TQ
.BR llabs ()
.TQ
.BR imaxabs ()
C23, POSIX.1-2024
.SH HISTORY
.TP
.BR abs ()
C89, POSIX.1-1996, SVr4, 4.3BSD.
.TP
.BR labs ()
C89, POSIX.1-2001.
.TP
.BR llabs ()
C99, POSIX.1-2001;
glibc 2.0.
.TP
.BR imaxabs ()
C99, POSIX.1-2001;
glibc 2.1.1.
.TP
.BR uabs ()
.TQ
.BR ulabs ()
.TQ
.BR \%ullabs ()
.TQ
.BR \%uimaxabs ()
C2y;
glibc 2.42.
.SH BUGS
For
.BR abs (),
.BR labs (),
.BR llabs (),
and
.BR imaxabs (),
trying to take the absolute value of the most negative integer
is not defined.
.SH SEE ALSO
.BR cabs (3),
.BR ceil (3),
.BR fabs (3),
.BR floor (3),
.BR rint (3)
