'\" t
.\" Copyright, The authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: GPL-1.0-or-later
.\"
.TH csqrt 3 (date) "Linux man-pages (unreleased)"
.SH NAME
csqrt, csqrtf, csqrtl \- complex square root
.SH LIBRARY
Math library
.RI ( libm ,\~ \-lm )
.SH SYNOPSIS
.nf
.B #include <complex.h>
.P
.BI "double complex csqrt(double complex " z );
.BI "float complex csqrtf(float complex " z );
.BI "long double complex csqrtl(long double complex " z );
.fi
.SH DESCRIPTION
These functions calculate the complex square root of
.IR z ,
with a branch cut along the negative real axis.
(That means that
.I csqrt(\-1+eps*I)
will be close to I while
.I csqrt(\-1\-eps*I)
will be close to \-I,
.I if eps
is a small positive real number.)
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lbx lb lb
l l l.
Interface	Attribute	Value
T{
.na
.nh
.BR csqrt (),
.BR csqrtf (),
.BR csqrtl ()
T}	Thread safety	MT-Safe
.TE
.SH STANDARDS
C11, POSIX.1-2008.
.SH HISTORY
glibc 2.1.
C99, POSIX.1-2001.
.SH SEE ALSO
.BR cabs (3),
.BR cexp (3),
.BR complex (7)
