.\" Copyright, The authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: GPL-2.0-or-later
.\"
.TH MB_CUR_MAX 3 (date) "Linux man-pages (unreleased)"
.SH NAME
MB_CUR_MAX \- maximum length of a multibyte character in the current locale
.SH LIBRARY
Standard C library
.RI ( libc )
.SH SYNOPSIS
.nf
.B #include <stdlib.h>
.fi
.SH DESCRIPTION
The
.B MB_CUR_MAX
macro defines an integer expression giving
the maximum number of bytes needed to represent a single
wide character in the current locale.
This value is locale dependent and therefore not a compile-time constant.
.SH RETURN VALUE
An integer in the range [1,
.BR MB_LEN_MAX ].
The value 1 denotes traditional 8-bit encoded characters.
.SH STANDARDS
C11, POSIX.1-2008.
.SH HISTORY
C99, POSIX.1-2001.
.SH SEE ALSO
.BR MB_LEN_MAX (3),
.BR mblen (3),
.BR mbstowcs (3),
.BR mbtowc (3),
.BR wcstombs (3),
.BR wctomb (3)
