.\" Copyright, Xavier Leroy <Xavier.Leroy@inria.fr>
.\" Copyright 2023, Alejandro Colomar <alx@kernel.org>
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.TH pthread_mutexattr_setkind_np 3 (date) "Linux man-pages (unreleased)"
.
.
.SH NAME
pthread_mutexattr_setkind_np,
pthread_mutexattr_getkind_np
\-
deprecated mutex creation attributes
.
.
.SH SYNOPSIS
.nf
.B #include <pthread.h>
.P
.BI "int pthread_mutexattr_setkind_np(pthread_mutexattr_t *" attr ", int " kind );
.BI "int pthread_mutexattr_getkind_np(const pthread_mutexattr_t *" attr ,
.BI "                                 int *" kind );
.fi
.
.
.SH DESCRIPTION
These functions are deprecated,
use
.BR pthread_mutexattr_settype (3)
and
.BR pthread_mutexattr_gettype (3)
instead.
.
.
.SH "RETURN VALUE"
.BR pthread_mutexattr_getkind_np ()
always returns 0.
.P
.BR pthread_mutexattr_setkind_np ()
returns 0 on success and a non-zero error code on error.
.
.
.SH ERRORS
On error,
.BR pthread_mutexattr_setkind_np ()
returns the following error code:
.TP
.B EINVAL
.I kind
is neither
.B PTHREAD_MUTEX_FAST_NP
nor
.B PTHREAD_MUTEX_RECURSIVE_NP
nor
.BR PTHREAD_MUTEX_ERRORCHECK_NP .
.
.
.SH "SEE ALSO"
.BR pthread_mutexattr_settype (3),
.BR pthread_mutexattr_gettype (3).
