'\" t
.\" Copyright, the authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: GPL-2.0-or-later
.\"
.TH wcscspn 3 (date) "Linux man-pages (unreleased)"
.SH NAME
wcscspn \- search a wide-character string for any of a set of wide characters
.SH LIBRARY
Standard C library
.RI ( libc ,\~ \-lc )
.SH SYNOPSIS
.nf
.B #include <wchar.h>
.P
.BI "size_t wcscspn(const wchar_t *" wcs ", const wchar_t *" reject );
.fi
.SH DESCRIPTION
The
.BR wcscspn ()
function is the wide-character equivalent
of the
.BR strcspn (3)
function.
It determines the length of the longest initial segment of
.I wcs
which consists entirely of wide-characters not listed in
.IR reject .
In
other words, it searches for the first occurrence in the wide-character
string
.I wcs
of any of the characters in the wide-character string
.IR reject .
.SH RETURN VALUE
The
.BR wcscspn ()
function returns the number of
wide characters in the longest
initial segment of
.I wcs
which consists entirely of wide-characters not
listed in
.IR reject .
In other words, it returns the position of the first
occurrence in the wide-character string
.I wcs
of any of the characters in
the wide-character string
.IR reject ,
or
.I wcslen(wcs)
if there is none.
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lbx lb lb
l l l.
Interface	Attribute	Value
T{
.na
.nh
.BR wcscspn ()
T}	Thread safety	MT-Safe
.TE
.SH STANDARDS
C11, POSIX.1-2008.
.SH HISTORY
POSIX.1-2001, C99.
.SH SEE ALSO
.BR strcspn (3),
.BR wcspbrk (3),
.BR wcsspn (3)
