.\" Copyright, the authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: GPL-2.0-or-later
.\"
.TH intro 8 (date) "Linux man-pages (unreleased)"
.SH NAME
intro \- introduction to administration and privileged commands
.SH DESCRIPTION
Section 8 of the manual describes commands
which either can be or are used only by the superuser,
like system-administration commands, daemons,
and hardware-related commands.
.P
As with the commands described in Section 1, the commands described
in this section terminate with an exit status that indicates
whether the command succeeded or failed.
See
.BR intro (1)
for more information.
.SH NOTES
.SS Authors and copyright conditions
Look at the header of the manual page source for the author(s) and copyright
conditions.
Note that these can be different from page to page!
