.\" Copyright, The contributors to the Linux man-pages project
.\"
.\" SPDX-License-Identifier: GPL-2.0-or-later
.\"
.TH intro 7 (date) "Linux man-pages (unreleased)"
.SH NAME
intro \- introduction to overview and miscellany section
.SH DESCRIPTION
Section 7 of the manual provides overviews on various topics, and
describes conventions and protocols,
character set standards, the standard filesystem layout,
and miscellaneous other things.
.SH NOTES
.SS Authors and copyright conditions
Look at the header of the manual page source for the author(s) and copyright
conditions.
Note that these can be different from page to page!
.SH SEE ALSO
.BR standards (7)
