.\" Copyright, The contributors to the Linux man-pages project
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.TH pathname 7 (date) "Linux man-pages (unreleased)"
.SH NAME
pathname,
filename
\-
how pathnames are encoded and interpreted
.SH DESCRIPTION
Some system calls allow you to pass a pathname as a parameter.
When writing code that deals with pathnames,
there are kernel-space requirements that you must comply with,
and user-space requirements that you should comply with.
.P
The kernel stores pathnames as C strings,
that is,
sequences of non-null bytes terminated by a null byte.
There are a few general rules that apply to all pathnames:
.IP \[bu] 3
The last byte in the sequence needs to be a null byte.
.IP \[bu]
Any other bytes in the sequence need to be non-null bytes.
.IP \[bu]
A 0x2F byte
.RI ( \[aq]/\[aq] )
is always interpreted as a directory separator,
and cannot be part of a filename.
.IP \[bu]
A pathname can be at most
.B PATH_MAX
bytes long
(see
.BR limits.h (0p)).
A pathname that's longer than
.B PATH_MAX
bytes
can be split into multiple smaller pathnames
and opened piecewise using
.BR openat (2).
.IP \[bu]
A filename can be at most a certain number of bytes long.
The number is filesystem-specific
(see
.B _PC_NAME_MAX
in
.BR fpathconf (3)).
For maximum portability,
programs should be able to
handle filenames that are as long as the relevant filesystems will allow.
For maximum portability,
programs and users should
limit the length of their own pathnames to
.B NAME_MAX
bytes
(see
.BR limits.h (0p)).
.P
Some filesystems or APIs may apply further restrictions,
such as requiring shorter filenames,
or restricting the allowed bytes in a filename.
.P
For maximum interoperability,
programs and users should also
limit the characters that they use for their own pathnames to
characters in the POSIX
.UR https://pubs.opengroup.org/\:onlinepubs/\:9799919799/\:basedefs/\:V1_chap03.html#tag_03_265
Portable Filename Character Set
.UE .
.SH SEE ALSO
.BR limits.h (0p),
.BR open (2),
.BR fpathconf (3),
.BR path_resolution (7),
.BR mount (8)
