'\" t
.\" Copyright (c) 2016 Michael Kerrisk <mtk.manpages@gmail.com>
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.TH signal-safety 7 (date) "Linux man-pages (unreleased)"
.SH NAME
signal-safety \- async-signal-safe functions
.SH DESCRIPTION
An
.I async-signal-safe
function is one that can be safely called from within a signal handler.
Many functions are
.I not
async-signal-safe.
In particular,
nonreentrant functions are generally unsafe to call from a signal handler.
.P
The kinds of issues that render a function
unsafe can be quickly understood when one considers
the implementation of the
.I stdio
library, all of whose functions are not async-signal-safe.
.P
When performing buffered I/O on a file, the
.I stdio
functions must maintain a statically allocated data buffer
along with associated counters and indexes (or pointers)
that record the amount of data and the current position in the buffer.
Suppose that the main program is in the middle of a call to a
.I stdio
function such as
.BR printf (3)
where the buffer and associated variables have been partially updated.
If, at that moment,
the program is interrupted by a signal handler that also calls
.BR printf (3),
then the second call to
.BR printf (3)
will operate on inconsistent data, with unpredictable results.
.P
To avoid problems with unsafe functions, there are two possible choices:
.IP (a) 5
Ensure that
(1) the signal handler calls only async-signal-safe functions,
and
(2) the signal handler itself is reentrant
with respect to global variables in the main program.
.IP (b)
Block signal delivery in the main program when calling functions
that are unsafe or operating on global data that is also accessed
by the signal handler.
.P
Generally, the second choice is difficult in programs of any complexity,
so the first choice is taken.
.P
POSIX.1 specifies a set of functions that an implementation
must make async-signal-safe.
(An implementation may provide safe implementations of additional functions,
but this is not required by the standard and other implementations
may not provide the same guarantees.)
.P
In general, a function is async-signal-safe either because it is reentrant
or because it is atomic with respect to signals
(i.e., its execution can't be interrupted by a signal handler).
.P
The set of functions required to be async-signal-safe by POSIX.1
is shown in the following table.
The functions not otherwise noted were required to be async-signal-safe
in POSIX.1-2001;
the table details changes in the subsequent standards.
.P
.TS
lb      lb
lw(24n) l.
Function	Notes
\f[B]abort\f[](3)	Added in POSIX.1-2001 TC1
\f[B]accept\f[](2)
\f[B]access\f[](2)
\f[B]aio_error\f[](3)
\f[B]aio_return\f[](3)
\f[B]aio_suspend\f[](3)	See notes below
\f[B]alarm\f[](2)
\f[B]bind\f[](2)
\f[B]cfgetispeed\f[](3)
\f[B]cfgetospeed\f[](3)
\f[B]cfsetispeed\f[](3)
\f[B]cfsetospeed\f[](3)
\f[B]chdir\f[](2)
\f[B]chmod\f[](2)
\f[B]chown\f[](2)
\f[B]clock_gettime\f[](2)
\f[B]close\f[](2)
\f[B]connect\f[](2)
\f[B]creat\f[](2)
\f[B]dup\f[](2)
\f[B]dup2\f[](2)
T{
.BR execl (3)
T}	T{
Added in POSIX.1-2008; see notes below
T}
\f[B]execle\f[](3)	See notes below
\f[B]execv\f[](3)	Added in POSIX.1-2008
\f[B]execve\f[](2)
\f[B]_exit\f[](2)
\f[B]_Exit\f[](2)
\f[B]faccessat\f[](2)	Added in POSIX.1-2008
\f[B]fchdir\f[](2)	Added in POSIX.1-2008 TC1
\f[B]fchmod\f[](2)
\f[B]fchmodat\f[](2)	Added in POSIX.1-2008
\f[B]fchown\f[](2)
\f[B]fchownat\f[](2)	Added in POSIX.1-2008
\f[B]fcntl\f[](2)
\f[B]fdatasync\f[](2)
\f[B]fexecve\f[](3)	Added in POSIX.1-2008
\f[B]ffs\f[](3)	Added in POSIX.1-2008 TC2
\f[B]fork\f[](2)	See notes below
\f[B]fstat\f[](2)
\f[B]fstatat\f[](2)	Added in POSIX.1-2008
\f[B]fsync\f[](2)
\f[B]ftruncate\f[](2)
\f[B]futimens\f[](3)	Added in POSIX.1-2008
\f[B]getegid\f[](2)
\f[B]geteuid\f[](2)
\f[B]getgid\f[](2)
\f[B]getgroups\f[](2)
\f[B]getpeername\f[](2)
\f[B]getpgrp\f[](2)
\f[B]getpid\f[](2)
\f[B]getppid\f[](2)
\f[B]getsockname\f[](2)
\f[B]getsockopt\f[](2)
\f[B]getuid\f[](2)
\f[B]htonl\f[](3)	Added in POSIX.1-2008 TC2
\f[B]htons\f[](3)	Added in POSIX.1-2008 TC2
\f[B]kill\f[](2)
\f[B]link\f[](2)
\f[B]linkat\f[](2)	Added in POSIX.1-2008
\f[B]listen\f[](2)
T{
.BR longjmp (3)
T}	T{
Added in POSIX.1-2008 TC2; see notes below
T}
\f[B]lseek\f[](2)
\f[B]lstat\f[](2)
\f[B]memccpy\f[](3)	Added in POSIX.1-2008 TC2
\f[B]memchr\f[](3)	Added in POSIX.1-2008 TC2
\f[B]memcmp\f[](3)	Added in POSIX.1-2008 TC2
\f[B]memcpy\f[](3)	Added in POSIX.1-2008 TC2
\f[B]memmove\f[](3)	Added in POSIX.1-2008 TC2
\f[B]memset\f[](3)	Added in POSIX.1-2008 TC2
\f[B]mkdir\f[](2)
\f[B]mkdirat\f[](2)	Added in POSIX.1-2008
\f[B]mkfifo\f[](3)
\f[B]mkfifoat\f[](3)	Added in POSIX.1-2008
\f[B]mknod\f[](2)	Added in POSIX.1-2008
\f[B]mknodat\f[](2)	Added in POSIX.1-2008
\f[B]ntohl\f[](3)	Added in POSIX.1-2008 TC2
\f[B]ntohs\f[](3)	Added in POSIX.1-2008 TC2
\f[B]open\f[](2)
\f[B]openat\f[](2)	Added in POSIX.1-2008
\f[B]pause\f[](2)
\f[B]pipe\f[](2)
\f[B]poll\f[](2)
\f[B]posix_trace_event\f[](3)
\f[B]pselect\f[](2)
\f[B]pthread_kill\f[](3)	Added in POSIX.1-2008 TC1
\f[B]pthread_self\f[](3)	Added in POSIX.1-2008 TC1
\f[B]pthread_sigmask\f[](3)	Added in POSIX.1-2008 TC1
\f[B]raise\f[](3)
\f[B]read\f[](2)
\f[B]readlink\f[](2)
\f[B]readlinkat\f[](2)	Added in POSIX.1-2008
\f[B]recv\f[](2)
\f[B]recvfrom\f[](2)
\f[B]recvmsg\f[](2)
\f[B]rename\f[](2)
\f[B]renameat\f[](2)	Added in POSIX.1-2008
\f[B]rmdir\f[](2)
\f[B]select\f[](2)
\f[B]sem_post\f[](3)
\f[B]send\f[](2)
\f[B]sendmsg\f[](2)
\f[B]sendto\f[](2)
\f[B]setgid\f[](2)
\f[B]setpgid\f[](2)
\f[B]setsid\f[](2)
\f[B]setsockopt\f[](2)
\f[B]setuid\f[](2)
\f[B]shutdown\f[](2)
\f[B]sigaction\f[](2)
\f[B]sigaddset\f[](3)
\f[B]sigdelset\f[](3)
\f[B]sigemptyset\f[](3)
\f[B]sigfillset\f[](3)
\f[B]sigismember\f[](3)
T{
.BR siglongjmp (3)
T}	T{
Added in POSIX.1-2008 TC2; see notes below
T}
\f[B]signal\f[](2)
\f[B]sigpause\f[](3)
\f[B]sigpending\f[](2)
\f[B]sigprocmask\f[](2)
\f[B]sigqueue\f[](2)
\f[B]sigset\f[](3)
\f[B]sigsuspend\f[](2)
\f[B]sleep\f[](3)
\f[B]sockatmark\f[](3)	Added in POSIX.1-2001 TC2
\f[B]socket\f[](2)
\f[B]socketpair\f[](2)
\f[B]stat\f[](2)
\f[B]stpcpy\f[](3)	Added in POSIX.1-2008 TC2
\f[B]stpncpy\f[](3)	Added in POSIX.1-2008 TC2
\f[B]strcat\f[](3)	Added in POSIX.1-2008 TC2
\f[B]strchr\f[](3)	Added in POSIX.1-2008 TC2
\f[B]strcmp\f[](3)	Added in POSIX.1-2008 TC2
\f[B]strcpy\f[](3)	Added in POSIX.1-2008 TC2
\f[B]strcspn\f[](3)	Added in POSIX.1-2008 TC2
\f[B]strlen\f[](3)	Added in POSIX.1-2008 TC2
\f[B]strncat\f[](3)	Added in POSIX.1-2008 TC2
\f[B]strncmp\f[](3)	Added in POSIX.1-2008 TC2
\f[B]strncpy\f[](3)	Added in POSIX.1-2008 TC2
\f[B]strnlen\f[](3)	Added in POSIX.1-2008 TC2
\f[B]strpbrk\f[](3)	Added in POSIX.1-2008 TC2
\f[B]strrchr\f[](3)	Added in POSIX.1-2008 TC2
\f[B]strspn\f[](3)	Added in POSIX.1-2008 TC2
\f[B]strstr\f[](3)	Added in POSIX.1-2008 TC2
\f[B]strtok_r\f[](3)	Added in POSIX.1-2008 TC2
\f[B]symlink\f[](2)
\f[B]symlinkat\f[](2)	Added in POSIX.1-2008
\f[B]tcdrain\f[](3)
\f[B]tcflow\f[](3)
\f[B]tcflush\f[](3)
\f[B]tcgetattr\f[](3)
\f[B]tcgetpgrp\f[](3)
\f[B]tcsendbreak\f[](3)
\f[B]tcsetattr\f[](3)
\f[B]tcsetpgrp\f[](3)
\f[B]time\f[](2)
\f[B]timer_getoverrun\f[](2)
\f[B]timer_gettime\f[](2)
\f[B]timer_settime\f[](2)
\f[B]times\f[](2)
\f[B]umask\f[](2)
\f[B]uname\f[](2)
\f[B]unlink\f[](2)
\f[B]unlinkat\f[](2)	Added in POSIX.1-2008
\f[B]utime\f[](2)
\f[B]utimensat\f[](2)	Added in POSIX.1-2008
\f[B]utimes\f[](2)	Added in POSIX.1-2008
\f[B]wait\f[](2)
\f[B]waitpid\f[](2)
\f[B]wcpcpy\f[](3)	Added in POSIX.1-2008 TC2
\f[B]wcpncpy\f[](3)	Added in POSIX.1-2008 TC2
\f[B]wcscat\f[](3)	Added in POSIX.1-2008 TC2
\f[B]wcschr\f[](3)	Added in POSIX.1-2008 TC2
\f[B]wcscmp\f[](3)	Added in POSIX.1-2008 TC2
\f[B]wcscpy\f[](3)	Added in POSIX.1-2008 TC2
\f[B]wcscspn\f[](3)	Added in POSIX.1-2008 TC2
\f[B]wcslen\f[](3)	Added in POSIX.1-2008 TC2
\f[B]wcsncat\f[](3)	Added in POSIX.1-2008 TC2
\f[B]wcsncmp\f[](3)	Added in POSIX.1-2008 TC2
\f[B]wcsncpy\f[](3)	Added in POSIX.1-2008 TC2
\f[B]wcsnlen\f[](3)	Added in POSIX.1-2008 TC2
\f[B]wcspbrk\f[](3)	Added in POSIX.1-2008 TC2
\f[B]wcsrchr\f[](3)	Added in POSIX.1-2008 TC2
\f[B]wcsspn\f[](3)	Added in POSIX.1-2008 TC2
\f[B]wcsstr\f[](3)	Added in POSIX.1-2008 TC2
\f[B]wcstok\f[](3)	Added in POSIX.1-2008 TC2
\f[B]wmemchr\f[](3)	Added in POSIX.1-2008 TC2
\f[B]wmemcmp\f[](3)	Added in POSIX.1-2008 TC2
\f[B]wmemcpy\f[](3)	Added in POSIX.1-2008 TC2
\f[B]wmemmove\f[](3)	Added in POSIX.1-2008 TC2
\f[B]wmemset\f[](3)	Added in POSIX.1-2008 TC2
\f[B]write\f[](2)
.TE
.P
Notes:
.IP \[bu] 3
POSIX.1-2001 and POSIX.1-2001 TC2 required the functions
.BR fpathconf (3),
.BR pathconf (3),
and
.BR sysconf (3)
to be async-signal-safe, but this requirement was removed in POSIX.1-2008.
.IP \[bu]
If a signal handler interrupts the execution of an unsafe function,
and the handler terminates via a call to
.BR longjmp (3)
or
.BR siglongjmp (3)
and the program subsequently calls an unsafe function,
then the behavior of the program is undefined.
.IP \[bu]
POSIX.1-2001 TC1 clarified
that if an application calls
.BR fork (2)
from a signal handler and any of the fork handlers registered by
.BR pthread_atfork (3)
calls a function that is not async-signal-safe, the behavior is undefined.
A future revision of the standard
.\" http://www.opengroup.org/austin/aardvark/latest/xshbug3.txt
is likely to remove
.BR fork (2)
from the list of async-signal-safe functions.
.\"
.IP \[bu]
Asynchronous signal handlers that call functions which are cancelation
points and nest over regions of deferred cancelation may trigger
cancelation whose behavior is as if asynchronous cancelation had
occurred and may cause application state to become inconsistent.
.\"
.SS errno
Fetching and setting the value of
.I errno
is async-signal-safe provided that the signal handler saves
.I errno
on entry and restores its value before returning.
.\"
.SS Deviations in the GNU C library
The following known deviations from the standard occur in
the GNU C library:
.IP \[bu] 3
Before glibc 2.24,
.BR execl (3)
and
.BR execle (3)
employed
.BR realloc (3)
internally and were consequently not async-signal-safe.
.\" https://sourceware.org/bugzilla/show_bug.cgi?id=19534
This was fixed in glibc 2.24.
.IP \[bu]
.\" FIXME . https://sourceware.org/bugzilla/show_bug.cgi?id=13172
The glibc implementation of
.BR aio_suspend (3)
is not async-signal-safe because it uses
.BR pthread_mutex_lock (3)
internally.
.SH SEE ALSO
.BR sigaction (2),
.BR signal (7),
.BR standards (7)
