#!/bin/sh

# Copyright 2023, Alejandro Colomar <alx@kernel.org>
# SPDX-License-Identifier: GPL-3.0-or-later

export LC_COLLATE=en_US.UTF-8;

sed   -E '/\/intro./ s/.*\.([[:digit:]])/\10\t&/' \
| sed -E '/\/intro./!s/.*\.([[:digit:]])\>/\11\t&/' \
| sed -E '/\/intro./!s/.*\.([[:digit:]][[:alnum:]]+)/\1\t&/' \
| sort \
| cut -f2;
