.\" Copyright, The contributors to the Linux man-pages project
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.TH diffman\-git 1 (date) "Linux man-pages (unreleased)"
.SH NAME
diffman\-git
\-
compare changes to manual pages line by line
.SH SYNOPSIS
.SY diffman\-git
.RI [ diff-options \~.\|.\|.\&]
.RI [[ base-commit ]
.IR commit ]
.YS
.SH DESCRIPTION
The
.B diffman\-git
command
formats a manual page at two
.BR git (1)
commits,
and then runs
.BR diff (1)
on the formatted outputs.
.P
If the
.I commit
is not specified,
it diffs the working directory against HEAD.
.P
If the
.I base-commit
is not specified,
the comparison is done against the previous commit.
.SH OPTIONS
.TP
.B \-s
Report when two files are the same.
.TP
.BI \-U n
output
.I n
(default 3)
lines of unified context.
.TP
.B \-w
Ignore all white space.
.SH ENVIRONMENT
See
.BR man (1).
.SH EXAMPLES
.EX
.RB $\~ "MAN_KEEP_FORMATTING= diffman\-git 437e4afec6ca | less \-R" ;
\-\-\- 437e4afec6ca\[ha]:man/man3/sem_open.3
+++ 437e4afec6ca:man/man3/sem_open.3
@@ \-14,3 +14,2 @@
\-     sem_t *sem_open(const char *name, int oflag);
\-     sem_t *sem_open(const char *name, int oflag,
\-                     mode_t mode, unsigned int value);
+     sem_t *sem_open(const char *name, int oflag, ...
+                     /* mode_t mode, unsigned int value */ );
.EE
.SH SEE ALSO
.BR diff (1),
.BR man (1),
.BR git (1),
.BR less (1)
