.\" Copyright 2024, Alejandro Colomar <alx@kernel.org>
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.TH pdfman 1 (date) "Linux man-pages (unreleased)"
.SH NAME
pdfman
\-
render a manual page in PDF
.SH SYNOPSIS
.B pdfman
.RI [ man-options ]
.RI [ section ]\~ page
.SH DESCRIPTION
The
.B pdfman
command renders a manual page in PDF.
All the arguments are interpreted by
.BR man (1).
.EE
.SH SEE ALSO
.BR man (1),
.BR groff (1),
.BR gropdf (1),
.BR xdg\-open (1)
