.\" Copyright, The authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.TH sortman 1 (date) "Linux man-pages (unreleased)"
.SH NAME
sortman
\-
sort manual-page path names
.SH SYNOPSIS
.SY sortman
.YS
.SH DESCRIPTION
The
.B sortman
command sorts manual-page path names
in the order that they should appear in the manual.
.P
The chapters and subchapters are first sorted.
Then, within each (sub)chapter,
the first page is the corresponding
.BR intro (*)
page,
and the rest are sorted alphabetically
(but treating specially some special characters).
.SH SEE ALSO
.BR intro (1),
.BR man (1),
.BR sort (1)
